### ISSUE TITLE
Investigate setting up a VPN from inside a namespace to connect to an external resource

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1016]
Spike running an IPSec VPN from inside a cluster namespace, using network policies to ensure that only objects inside the namespace can access the VPN (and vice versa).

This is so that we're prepared, before a team asks us for this.

Windows-centric article, using OpenVPN

    https://caveofcode.com/2017/06/how-to-setup-a-vpn-connection-from-inside-a-pod-in-kubernetes/

**Comment by vijay-veeranki-moj** [comment]
![Plan.png](https://images.zenhubusercontent.com/5cd14e5c7c13c23a96974cd6/b9620ce6-fd93-43f6-8ae5-1f169635f70d)

**Comment by vijay-veeranki-moj** [comment]
The above Plan is to IPSec VPN from inside a cluster namespace, using network policies to ensure that only objects inside the namespace can access the VPN.

What we would need is a way to allow all pods in a customer's namespace access to the customer's VPN.

To achieve this, created a test cluster and deployed IPsec VPN as a pod in a namespace using helm chart(https://github.com/ChrisPhillips-cminion/vpn-helm).

To test the connectivity created a Ec2 instance running Nginx on it and created a Single Site-to-Site VPN Connection
https://docs.aws.amazon.com/vpn/latest/s2svpn/Examples.html
1.    Create AWS Customer gate way using the Server IP: from the IPsec VPN server, running in a Pod.
2.	Setting up the VPN endpoint on AWS. This provides an IP address you connect to from our IPsec VPN, given that as an external IP option we have while creating an IPsec VPN using helm-chart.
3.	Downloading the AWS VPN connection configuration and setting up the VPN connection by changing the ipsec.config  of IPsec pod . This step in theory joins it all together.

While research couldn't find an option in the IPSec config or network policies to limit to a single namespace.

In research for the topic, I found approaches that add a VPN client to the individual container (e.g., https://caveofcode.com/2017/06/how-to-setup-a-vpn-connection-from-inside-a-pod-in-kubernetes/) which is not an option for us). 

Other approaches are running a VPN server inside K8s (which is also not what we need). 

"Strongswan IPSec VPN service", https://www.ibm.com/blogs/bluemix/2017/12/connecting-kubernetes-cluster-premises-resources/ ) use DaemonSets to "configure routing on each of the worker nodes". 
This also does not seem like a solution that is acceptable to us, since that would allow all pods (irrespective of the namespace they are in) on a worker node access to the respective VPN).

Also there are some considerations using Strongswan IPSec VPN https://cloud.ibm.com/docs/containers?topic=containers-vpn#strongswan_limitations

Creating a VPN inside a pod is is useful during development to access your applications (pods) inside your Test Kubernetes cluster without creating an external (public) endpoint.
making life much easier for development environments where developers cannot run the entire app stack locally but need to iterate on 1 app quickly.

But for our scenario it is not helpfull as we cannot limit it to a namespace.
