### ISSUE TITLE
SPIKE: Consider Sentry.io

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1057]
## Background

User need to be able to receive exception reporting for their products so that they can provide application support. At present we use Sentry for this task.

The current Sentry instance is based on Template Deploy and supported by the Cloud Platform team. We will be decommissioning Template Deploy so need to understand out options for providing this service longer term for our users.

A couple of options have been considered:

1. Adopt the managed service Sentry.io
2. Recreate an instance of Sentry that we manage on the new Cloud Platform.

Both are viable options, however moving to Sentry.io will reduce the burden of support for the team and reduce costs (costs associated with the team maintaining our own infrastructure).

However, there were some concerns around adopting a managed service and the sorts of information we might expose as a result.

There will also be a migration activity as users who have moved to the Cloud Platform use the legacy instance of Sentry.

We need to understand more about this service so that we can determine which option to implement.

## Proposed user journey

N/A

## Approach

This is a spike story. Determine answers to the questions raised below.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

We should be able to answer these questions as a result of this spike:
- What data will we expose to Sentry.io?
- What security controls are in place to protect our information?
- What guidance may be required to ensure that Service Teams don't expose sensitive information?
- What differences are there with the existing service that might be visible to users or change how they interact with the existing Sentry?
- What is the migration path from TD Sentry to Sentry.io (consider how this might differ is we rebuilt the service on Cloud Platform)
- Can we do this transparently for our users or do users need to be involved in migration?
- What other considerations do we need to make around migration? 
- How much will it cost?
- What support do we get?
- Who will manage accounts (joiners/movers/leavers)? how?
- Are there any new features of Sentry.io that our users could benefit from?

## Definition of done

- [ ] we have answers to the questions raised for this spike so that we can make a decision on next steps.
- [ ] we have security approval to adopt this product.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by digitalronin** [comment]
Comments from Amit in the security team:

> My 2c: A service with good availability, decent security controls, access logs could improve our security posture so not automatically a bad idea from a security PoV at all. Need some confidence about how the provider manages and secures their service - the questions raised in the ticket seem to cover this, and I think it would be good to work through the scenario of needing to expunge something from the service e.g. we’ve accidentally logged some PII, how do we delete it everywhere and how long does it take to happen

https://mojdt.slack.com/archives/C52LPHPK8/p1578568324009000

**Comment by digitalronin** [comment]
## What data will we expose to Sentry.io?

Events which are logged with the service include timestamps, project names, source code filenames and code snippets, information about the execution environment of the originating service (eg. OS version, build number, software library versions), plus whatever information the developers chose to include in their exception handling code.

## What security controls are in place to protect our information?

The sentry.io service requires authentication in order to access information belonging to our organisation.

Currently, this authentication is via email address and password, with an "invite" email going out to the relevant address when the user is invited, to confirm that they do actually control that email address. Once we have the business plan, we will convert this to authenticate via github, in line with the rest of MoJ Digital services, so that we benefit from more reliable JML processes, and enforcement of 2FA requirements (we could also enable this while using email+password).

https://docs.sentry.io/accounts/membership/

sentry.io provides some management features to try and prevent logging personally identifying information (PII), although of course developers are discouraged from doing this in the first place.

https://docs.sentry.io/data-management/sensitive-data/#server-side-scrubbing

## What guidance may be required to ensure that Service Teams don't expose sensitive information?

Sentry.io has some good guidance on this:
https://docs.sentry.io/data-management/sensitive-data/

## What differences are there with the existing service that might be visible to users or change how they interact with the existing Sentry?

The differences are slight, since the sentry.io offering is just a later version of the self-hosted https://sentry.service.dsd.io/ we currently use.

A key difference is that the email integration works. I know the lack of working email integration is a significant problem for some of our teams.

## What is the migration path from TD Sentry to Sentry.io (consider how this might differ is we rebuilt the service on Cloud Platform)

Projects & teams will need to be recreated, and any existing sentry software libraries that teams are using will need to be updated to the current version, and configured to point at the sentry.io URL rather than sentry.service.dsd.io

## Can we do this transparently for our users or do users need to be involved in migration?

Users will need to make these changes themselves.

## What other considerations do we need to make around migration?

Any teams who are logging excessive details, PII or authentication credentials because they feel safe that the information is only going to a self-hosted sentry instance will need to reconsider their life choices.

## How much will it cost?
## What support do we get?
## Who will manage accounts (joiners/movers/leavers)? how?
## Are there any new features of Sentry.io that our users could benefit from?

**Comment by digitalronin** [comment]
>  it would be good to work through the scenario of needing to expunge something from the service e.g. we’ve accidentally logged some PII, how do we delete it everywhere and how long does it take to happen

The sentry.io interface has options to permanently remove data by various criteria:

https://docs.sentry.io/data-management/sensitive-data/#removing-data

I have asked for more detail about exactly what happens if we use those features.

**Comment by digitalronin** [comment]
Further questions (copied from slack):

1. What is the exit strategy - can we reclaim our data easily and migrate to another platform if circumstance demand.
2. You mention an SLA, has it been reviewed yet?
3, How is the data stored (I could not see this on the website) - is it encrypted and how resilient is the system - what and where is it hosted? (Data in transit is over https so that seems good).
4. Where is the Sentry support provided from and do the staff need any clearance to handle the data they are exposed to?
Thanks,

**Comment by digitalronin** [comment]
I've passed the above questions on to Angela Xin at Sentry.io

I'll update here if I get any useful response.

**Comment by AntonyBishop** [comment]
Response to addition questions:

Hi Simon,

Have had some additional information back based on your follow up questions:

1. Exit Strategy - There are a few elements to this. There there two types of data that we are interested in. The triggers that we create to send data to Sentry.io and the actual event data. The case of the event data this is only retained for 90 days, after which the data is deleted. There is no archiving of data. So in the event of exit we would be able to export any data that we wish to retain that is within that 90 days, including any triggers. At the point in time that we terminate the contract for the service Sentry's docs confirm "All customer data stored on Sentry servers is eradicated upon a customer’s termination of service and deletion of account after a 24-hour waiting period to prevent accidental cancellation. Data can also be deleted upon request and via Sentry’s REST API and UI." So if needed we could delete our own data sooner that 24 hours.

2. SLA - This will be discussed as part of contract initiation. It sounds like this is negotiable. However, any SLA will be better than what we have for the unsupported instance we host now. 

3. How is data stored? - From the Sentry.io docs (https://sentry.io/security/#data-security-and-privacy) - "All data in Sentry servers is encrypted at rest. Google Cloud Platform stores and manages data cryptography keys in its redundant and globally distributed Key Management Service. So, if an intruder were ever able to access any of the physical storage devices, the Sentry data contained therein would still be impossible to decrypt without the keys, rendering the information a useless jumble of random characters.

Encryption at rest also enables continuity measures like backup and infrastructure management without compromising data security and privacy.

Sentry exclusively sends data over HTTPS transport layer security (TLS) encrypted connections for additional security as data transits to and from the application."

It sounds like generically Sentry host on Google Cloud which could be geographically anywhere. However we can request a Single Tenant "If your organization requires data isolation, Sentry has introduced Single Tenant instances of our platform.

With Single Tenant, your resources and liabilities are not shared with other tenants as your data at rest remains isolated.

Single tenant instances can be spun up in various geographic regions."

So that is something we can request.

4. Support is provided from USA (San Francisco, California). Sentry staff are "security cleared" but Sentry don't offer much detail on this. It sounds like "Basic Check". Sentry's docs also confirm "Sentry employees do not have physical access to Google data centers, servers, network equipment, or storage."

**Comment by AntonyBishop** [comment]
Ready for Triage resubmission.
