### ISSUE TITLE
documentation error in ecr module

### ISSUE THREAD

**Issue by asmega** [ministryofjustice/cloud-platform#1068]
## Service name

https://github.com/ministryofjustice/cloud-platform-terraform-ecr-credentials

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [X] Other

## Impact on the service

n/a

## Problem description

The README states that `providers` in not required therefore optional. this is not the case and concourse planning fails. Can the documentation be changed to reflect this.

Also can the module implement the default `provider` list. I don't see why the defaults can't come out of the box, instead of every user needing to implement these

Failing build for reference https://concourse.cloud-platform.service.justice.gov.uk/builds/16519

## Contact person

Phil Lee (me)

**Comment by mtrblmoj** [comment]
This issue was due to the complexity of the upgrade path. 
Due to some compatibility-breaking changes in version 3.2, it was impossible to go from 3.1 to 3.4 directly. 

All ECR have now been upgraded past the broken version. I'll make sure it is not possible to install that version anymore.

This documentation task is not required anymore. 
@AntonyBishop happy to close this ticket ?

**Comment by AntonyBishop** [comment]
Happy to close.
