### ISSUE TITLE
Runbook for how to add nodes to the cluster

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1075]
## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by mtrblmoj** [comment]
We have done this on 15/07/19  - Jobs/Pod could not get scheduled because no more CPU was available.

We bumped the number of nodes :
 - kops export kubecfg <live-1>
 - upgrade kops version to 12.12
 - kops edit ig 
   - AutoscalingGroup/
  	MaxSize             	 18 -> 21
  	MinSize             	 18 -> 21
 - kops  update cluster live1 
 
Next step is to persists the change terraform/cloud-platform

**Comment by mtrblmoj** [comment]
done again 21-> 40 nodes
