### ISSUE TITLE
SPIKE: Investigate why teams are unable to use application specific 404 error pages

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1122]
## Background

We are having reports from teams (e.g. Formbuilder) that 404 errors are returning the Cloud Platform custom error page rather than their own 404 error page.

This is an issue for teams as the custom page is generic and the teams what to serve up something more specific for their application.

We believe this should be possible without changing the design of the cluster but wish to investigate further.

## Proposed user journey

In the event of a 404 error a product will use an application specific error page, if one exists, otherwise the Cloud Platform custom error page.

## Approach

Work with users who have raised this issue to understand why this is not working as expected.

## Which part of the user docs does this impact

N/A

## Definition of done

- [x] We can replicate this issue
- [x] We understand why the issue occurs
- [x] We have a solution to address the issue
- [x] We understand what documentation might be needed for users

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki-moj** [comment]
As teams facing issues to have the application serve 404s after applying our default-backend page with custom-http-errors: 400,403,404,413,502,504.

Updated config to `custom-http-errors: 413,502,503,504` to unblock teams having issues.

Solution to fix this problem is let user control for what error code they want to serve the default error page.
We need to remove  `custom-http-errors` at nginx-ingress level, and get teams to configure that in their ingress level, by adding annotation.

For example they want to serve only 503 from our default backend they need to add annotation in their ingress 

```
  annotations:
    nginx.ingress.kubernetes.io/custom-http-errors: "503"
```

we need to request teams to update their ingress with above annotation before we apply those changes.

**Comment by vijay-veeranki-moj** [comment]
Also created a user-guide for users create custom-default backend in a namespace

https://github.com/ministryofjustice/cloud-platform-user-guide/pull/131
