### ISSUE TITLE
Create an integration test for custom error pages

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1151]
* Test that the cluster default 404 page is shown (this already exists)
* Test that a namespace with zero replicas (should deliver 504 error), shows the custom error page
* Test that a namespace can override whatever error codes they want, with their own pages

**Comment by vijay-veeranki-moj** [comment]
Moved to blocked, as below scenario is not working, when tested with multiple error codes.
 
`Test that a namespace can override whatever error codes they want, with their own pages.`

This issue was fixed in later ingress-contoller release.`https://github.com/kubernetes/ingress-nginx/pull/3730`

But tested it in test-cluster upgrading to that release, it is still not working, where custom error codes are not working with default backend as expected.

Raised this with nginx-ingress-contoller team, look at the below issues.

https://github.com/kubernetes/ingress-nginx/issues/3700
https://github.com/kubernetes/ingress-nginx/issues/4576

This can only be tested again after nginx-ingress-contoller team, address this issue.

**Comment by vijay-veeranki-moj** [comment]
These are the tests, written for default-backend.

https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/393

Once it is unblocked it can be picked up. 

Also use the https://github.com/ministryofjustice/cloud-platform-http-error-handler
to get the http errors

**Comment by vijay-veeranki-moj** [comment]
Nginx-Ingress controller team fixed default-backend issue in this version.
https://github.com/helm/charts/blob/master/stable/nginx-ingress/Chart.yaml

This will get unblocked when we upgrade our ingress controller to the latest helm chart version.
