### ISSUE TITLE
Decision to remove services we don't support

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#116]
This ticket connects to #115 

### Background
Changes in how and what we monitor need to be agreed upon and communicated

### Aim
All services and their checks are classified; owner teams are identified and informed of the proposed changes

### DOD
A spreadsheet linking lists from high alerts (#115), low alerts (#125), external (#117) and internal () services and  is available in GDocs
Agreement within the CP team on which will be changed
Conclusions sent to owner teams

**Comment by sablumiah** [comment]
The following were setup within the out of hours team (high priority) however were also not set up to alert:

Family Mediators https://prod.familymediatorsapi.dsd.io/api/v1/healthcheck
LPA https://gateway.nomis-api.service.justice.gov.uk/
Nomis API https://gateway.nomis-api.service.justice.gov.uk/

There were reassigned to appropriate teams within Pagerduty.  however, as these were not setup to monitor in the first place (to an email or slack channel) they will still not alert. 

Service Catalogue: Production Systems IRAT was deleted due to being a CP product which was not finished and never setup completely. 

https://docs.google.com/spreadsheets/d/1kMgmJrOlUZZKD2DO1ufqeL_Q0tY9X18XXJWn9Hfdx6c/edit?usp=sharing
