### ISSUE TITLE
AWS SQS resource creation issue

### ISSUE THREAD

**Issue by lbennett-moj** [ministryofjustice/cloud-platform#1183]
## Service name

Offender-categorisation

## Service environment

- [ ] Dev / Development

## Impact on the service

Unable to create aws sqs resources required for asynchronous service communication 

## Problem description

cloud platform pipeline fails with the following error
```
1 error occurred:
    * aws_sqs_queue_policy.risk_profiler_change_policy: 1 error occurred:
    * aws_sqs_queue_policy.risk_profiler_change_policy: Error updating SQS attributes: AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
    status code: 400, request id: c3be9266-018e-5bb5-a634-c7b6d2494e16

```
## Contact person

slack lucyb
email lucy.bennett@digital.justice.gov.uk

**Comment by vijay-veeranki-moj** [comment]
This is caused because of the region.

The module is created in london region

provider "aws" {
  alias  = "london"
  region = "eu-west-2"
}

where as the resource "aws_sqs_queue_policy"  is looking for the sqs queue in 
provider "aws" {
  region = "eu-west-1"
}

To fix this change the default region to region = "eu-west-2", so it can find the queue in london region and apply the policy

**Comment by lbennett-moj** [comment]
Hi Vijay

Good spot - can't believe I missed that!

I'll raise another PR.

Thanks

Lucy

**Comment by vijay-veeranki-moj** [comment]
Hi @lbennett-moj

Please test it changing the region in main.tf as below, this will fix the issue.

provider "aws" {
region = "eu-west-2"
}
