### ISSUE TITLE
Investigate missing tagging for PVB and MTP

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#127]
**Background**
In a previous sprint we tagged our infrastructure in line with the latest tagging Policy.

Since then some reporting has been run and tagging appears to be missing for Prison Visits Booking and Money to Prisoners.

This story has been created to determine if the tagging took place, and if it did, why it isn't in the reporting.

Any corrective action will take place under a new ticket.

Information is being requested by Alex Clark.

**Definition of Done**
- [x] We understand why information was not being reported
- [x] We can raise a new story for corrective action for the backlog
- [x] Finding recorded in this Issue

**Comment by nayoa** [comment]
After discussion with Alex Clark, he confirms that only 12 applications are showing in Cost Explorer instead of 28 showing in the below document (Intranet not included) - https://docs.google.com/spreadsheets/d/1y4i5d4YYj8rnkGFLLCZcnj5_i_mwI1kQZz9rs0OgQDI/edit?usp=sharing

At first glance on the mojdsd account, it appears that the tags are not all of the tags are being picked up by cost explorer. I.e. only seeing business-unit, environment-name and is-production. Will double check the tagging in mojdsd and refer back to cost explorer. A ticket will need to be raised with mojdsd support to raise the issue.

**Comment by nayoa** [comment]
After discussion with Ben Paton (AWS TAM) it appears that in Billing > Cost Allocation Tags on AWS Master Account, we have only activated the following tags:

- business-unit 
- application
- is-production
- environment-name

The following tags have now been activated so should appear as of tomorrow - 

- infrastructure-support
- runbook
- source-code
- owner
- component

Note:
The reason why PVB and MTP were not showing in cost explorer was due to the fact that everything in the 'mojdsd' account has been tagged with the tag key 'Application' opposed to 'application'. Cost explorer and tagging is case sensitive and could therefore was not picked up. 

The next step is to go through tagging on all accounts starting with mojdsd and ensure that the tag key aligns to the tagging scheme and the tag keys are exactly the same as the above.

**Comment by nayoa** [comment]
Tag key in 'mojdsd' has been changed to 'application' instead of 'Application' to reflect the tagging policy. The applications in mojdsd, including PVB and MTP and now visible in the 'mojmaster' account in Cost Explorer.

**Comment by nayoa** [comment]
How to review - Check Cost Explorer on 'mojmaster' account to see if applications are visible in the tag filter. 

On intial viewing, it looks like the case senstitive issue has effected the business-unit, component and infrastructure-support values. Potentially a new ticket can be crafted to address this issue.

**Comment by sid234** [comment]
MoJ Tagging standard -
https://ministryofjustice.github.io/technical-guidance/standards/documenting-infrastructure-owners/#tagging-your-infrastructure
