### ISSUE TITLE
Check and add services that we support that are not on the list

### ISSUE THREAD

**Issue by ollieanwyll** [ministryofjustice/cloud-platform#129]
This ticket connects to #115 #125 

Once we have discovered the services that we support and the ones that are on our alerts list, we should then add then add those missing supported services to the list alerting system.
This ticket is to check and add services that we support that are not on the list, to the PD alerts list.

**Comment by sablumiah** [comment]
Money to Prisoners and Find a legal aid advisor were not alerting into Pagerduty.
Both services did have a Pingdom monitor, so that was used to create a pingdom webhook within Pagerduty so now alert out of hours high priority team. 

https://docs.google.com/spreadsheets/d/1kMgmJrOlUZZKD2DO1ufqeL_Q0tY9X18XXJWn9Hfdx6c/edit?usp=sharing
