### ISSUE TITLE
Perform fab update for Correspondence-staff-deploy template deploy

### ISSUE THREAD

**Issue by mseedat-moj** [ministryofjustice/cloud-platform#1319]
## Service name
Track a query (Correspondence_tool_staff)
https://github.com/ministryofjustice/correspondence_tool_staff/pulls

## Service environment

- [X] Dev / Development
- [X] Staging
- [X] Prod / Production
- [X] Other (demo)

## Impact on the service
Production environment to be updated with notice

## Problem description
Secrets in the template deploy project have been updated but the 

## Contact person

Mo seedat (slack) 
mohammed.seedat@digital.justice.gov.uk

**Comment by pwyborn** [comment]
21/10/2019 paulwyborn:palm_tree: 10:02 AM
Hi - Mo -sorry have been off (am actually off today). However I have run fab updates on all environments except prod. Can you let me know if it all looks ok please - before I run on prod?

21/10/2019 Mo Seedat 10:35 AM
Great thanks will check

new messages
21/10/2019 Mo Seedat 11:47 AM
Hi @paulwyborn this seems to be working as expected. thanks for doing that. Can we hold back on production until tomorrow please?

21/10/2019 paulwyborn:palm_tree: 12:17 PM
Yes sure

**Comment by pwyborn** [comment]
paulwyborn 22/10/2019 - 9:09 AM
Mo - let me know in due course - the time you want prod to be updated please? I’m here until 16:00 (edited) 
Mo Seedat  22/10/2019 9:11 AM
Will do thanks Paul

**Comment by pwyborn** [comment]
paulwyborn 3:33 PM
Seemed to work on most instances - seems to have been a problem with one instance failing 34.243.254.113 - just looking at it. In the meantime can you just confirm that the site is up and running - please Mo?
paulwyborn 3:42 PM
That instance does not appear to be on the load balancer. Just auto-scaling up another to see if that is healthy
Mo Seedat 3:51 PM
yes working as expected - 2 instances out of 4 were switched off due to issues. @Mourad Trabelsi has more info. We settled on leaving 2 on and bumped up the timeout for cpu/memory due to high load in bursts when using redis.
