### ISSUE TITLE
Investigate why Prometheus queries take a long time

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1602]
There are a number of theories:
- lack of memory on the worker nodes
- too much data
- EBS is too slow to query
- There are too many threads in use to query

**Comment by sablumiah** [comment]
Since this ticket was created, we have upgraded prometheus-operator to the latest release, and the jenkins instance that was importing 100s of metrics with data has been decomd. It is not possible to recreate the above issues on demand and they are not happening at the moment.

This ticket will placed in blocked for a few weeks incase the issues arise again.
