### ISSUE TITLE
Migrate from hosted sentry to https://sentry.io

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1614]
related to #1057

We have at least one instance of Sentry running in the moj-dsd AWS account.

This hasn't been patched/upgraded for years, but we believe one or more teams
are still using it for their exception alerting.

We need a plan for getting teams to migrate to the hosted service at sentry.io

* Audit the sentry instance, and find out who is using it, and for what
* Contact the relevant teams and help/encourage them to migrate to the hosted service
* Pick and announce a shutdown date for the hosted instance
* Kill it

Actions so far:

* Trial account created
* Pinged Kath Pobee-Norris and Ryan Brooks to see if they'd be willing for their teams to act as guinea pigs
* Pinged Steve to get the trial account upgraded to a business account
* Triage Approval for adopting Sentry.io received
* Contracts signed and PO in place
* Requested trial account be converted
* Account and support all set up. Ready to start migration activities.

**Comment by digitalronin** [comment]
The prisoner money team have started using sentry.io

**Comment by AntonyBishop** [comment]
Thanks for starting your journey with Sentry! We're so excited to have you on board and hope that Sentry helps you and your team fix bugs faster - and maybe even ship better code.

Getting started is super easy! Follow this guide for a detailed introduction to your Sentry account. Then, be sure to check the following resources to make the most out of your Sentry experience:
Watch our Webinar on how to best implement and configure Sentry.
Watch and share this demo that covers shares best practices in getting started with Sentry.
For use-case-specific best practices, our guides provide step-by-step instructions to some of Sentry's most powerful features.
*Our documentation houses a lot of answers to frequently asked questions*
You can follow updates that we are making to the product, request features/updates, read about the questions other customers have and chat with them on our GitHub page. Our engineers also jump in from time to time and answer questions there.
Subscribe to our Blog and/or YouTube channel for announcements and additional helpful content
You can post questions to our community using our Support Forum.
You can also subscribe to our Status Page so that if anything goes down, you will be notified
If you need to report a bug or if our documentation/forum doesn't answer your question, you can create a ticket from within the Sentry's UI or email our Support Team directly at support@sentry.io. For questions regarding your contract, please feel free to reach out to me and I'll be happy to assist you.

Thank you!

**Comment by AntonyBishop** [comment]
Services migrated.
