### ISSUE TITLE
Set up Gitrob for operational security team

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#168]
## Background

We've agreed that as the first part of #97 we will set up [Gitrob](https://github.com/michenriksen/gitrob) for the operational security team to use to scan git repos and act on the potential leakage of secrets from GitHub repositories. 

## Proposed user journey

- The operational secuity team will go to a dashboard once a day
- They will see a summary of the potential leaks
- They will get in touch with the repo owners to work out a resolution

## Approach

We will install Gitrob as an app on Kubernetes. We will need to have a way to build and deploy it onto the cluster (this could be manual but it will need documentation). 

Once we have it running and can confirm that the dashboard clearly shows when there is a potential leak we will provide the URL to the operational security team. 

## Questions / Assumptions

- This is a bit of a PoC at the moment, our support will be best efforts. 
- We think that gitrob can continuously scan the diff and look at that for new secrets. If it can't then we want it to run regularly without overwhelming time and resources. (We want it to scale to 1000+ repos) 
- Only a defined list of users (Github creds?) can read the reports

## Definition of done

- [ ] Created a read only credential for the whole github org
- [ ] Gitrob is running on a URL that the operational security team can access
- [ ] Only the operational team can access said URL
- [ ] Gitrob is running on `live-0` cluster 
- [ ] Gitrob runs periodically against the whole github org
- [ ] We want to test that it picks up a "fake secret" -- e.g. commit a fake secret and check that it gets picked up
- [ ] Documentation on how it is deployed (README) 

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
Notes so far:
- App has just had a full rewrite, the current release lacking some previous features like authentication and persistence in a database; author doesn't support previous releases and has closed all related GH issues
- App does work, at a basic level, runs in a Docker container at http://52.215.27.147:8080/ (reachable from office IPs)
- App scans all the repos of all users in the org, even those they might consider as not related to work 
- Full scan is slow, mostly because of the too wide scope; will need to make sure the saession save/load works properly
![screen shot 2018-06-19 at 10 17 38](https://user-images.githubusercontent.com/36888774/41588637-3ab9c868-73aa-11e8-87c0-d9edfccde78d.png)
- Output is not paginated
- Too many false positives:
 - matching is very basic, looking for strings like 'password' or well-known file names like 'settings.py' but without inspecting their actual contents
 - git-crypted files are also flagged

**Comment by razvan-moj** [comment]
Since Gitrob code doesn;t seem mature enough, agreed to spike timeboxed 1 day:
 - Sid https://github.com/auth0/repo-supervisor
 - Ashley https://github.com/We5ter/Scanners-Box
 - razvan https://github.com/UKHomeOffice/repo-security-scanner

**Comment by kalbir** [comment]
@razvan-moj could you create a new ticket for that spike and capturing the results? As this one is a bit Gitrob specific it will get confusing quickly! Then when we decide what to do we can close this ticket and raise a new (similar) one for the new approach.

**Comment by razvan-moj** [comment]
Output of a minimal test of Gitrob is in https://github.com/ministryofjustice/cloud-platform-gitrob
Created #172 to work on the spike above, this story can be closed
