### ISSUE TITLE
Server 500 error for admin log in on Find a legal advisor

### ISSUE THREAD

**Issue by Katherineod** [ministryofjustice/cloud-platform#178]
## Service environment

- [ ] Dev / Development
- [ ] Staging
- [/ ] Prod / Production
- [ ] Other

## Impact on the service
The tool needs to be updated monthly with a list of advisors.  The team who do this cannot log into the admin to complete this task (Server Error 500) https://prod.laalaa.dsd.io/admin/login/?next=/admin/  This means: 

- Providers who have withdrawn or terminated won’t be removed the FALA tool online and we will still be giving their details to members of the public looking for legal advice
- Providers are updating their address details – The LAA are currently updating over 250 office details and so address details may be out of date for providers 
- A provider may withdraw from a specific category of law 

## Problem description

The team responsible for updating the list of providers cannot access the admin site, and are getting a Server Error 500
https://prod.laalaa.dsd.io/admin/login/?next=/admin/ 

We’d like to be able to see the logs for this service - could you let me know where these are? 
## Contact person

Katherine O'Doherty @katherine o'doherty 
#get-access

**Comment by lukaszraczylo** [comment]
- Checked sentry to get server id ( I-04f2f040207b9b4f3 ), container ( d9c200c9c1ae )
- Killed all containers running on the server
- Cleaned up disk space, removed dangling containers and images
- Kickstarted containers using init scripts
- Confirmed that admins can log in

**Comment by rowlando** [comment]
@lukaszraczylo 

This error has reoccurred. 

I don't know if it's related to https://sentry.service.dsd.io/mojds/laalaaprod/issues/2973/ which started happening after the deploy.

Can you help?

**Comment by Katherineod** [comment]
Is this ticket being prioritised or would we be better opening a new one?

**Comment by lukaszraczylo** [comment]
Website throws 500 after logging in, yet after the page refresh, the admin panel is still visible and usable.

**Comment by lukaszraczylo** [comment]
LAA outage
- Team notified us on 500 errors during file upload
- One of the servers (2) was out of sync and both servers were running different versions of the application container
- Server (2) was out of disk space - I’ve performed the cleanup on old kernels which increased the free space
- I still wasn’t able to run successful fab update on mentioned server due to docker version mismatch
- I have terminated both of the servers waiting for autoscaling group to bring them back up
- After servers came back into the service issue with RMQ and erlang version incompatibility appeared preventing daemon from start
- I have installed latest deb package for rabbitmq on both of the servers and RMQ started up with no further issues
- ELB for laalaa prod showed both instances in service but domain kept returning 500
- Tried to deploying latest version of laalaa using CI when SSL lib issue on the Jenkins appeared. I’ve asked Razvan for help on this
- After checking load balancers in the account I have figured out that domain points to prod1 ELB ( which was a leftover from the different stack ) and mentioned ELB had no instances attached to it as it wasn’t part of the stack itself.
- I have manually added servers to the ELB and website came back up
- Team confirmed that everything is back up
