### ISSUE TITLE
Template-deploy assistance

### ISSUE THREAD

**Issue by said-moj** [ministryofjustice/cloud-platform#1784]
## Service name

Civil Legal Aid

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Unable to upgrade to supported LTS version of RDS postgres

## Problem description
We are looking to upgrade our cla-prod RDS instance from postgres 9.4 to 9.6. However this has a read-replica (cla-prod-read-replica) which [cannot undergo a major version upgrade](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html). We are looking to upgrade cla-prod(master) instance first then create a new read-replica. However our application would still reference the old read-replica.

We require someone from cloud-platforms to deploy our template-deploy repository https://github.com/ministryofjustice/cla_backend-deploy after we have changed the reference to the old read replica host name.

This needs to be done on a Monday  before 8AM

Can you please assign us someone that can do deploy template-deploy repositories and let us know so that we can plan our upgrade work.

## Contact person
[at]Said
[hash]laa-cla-fala

**Comment by said-moj** [comment]
Hi. Any update on this ticket please? We need to do the original work outside working hours and would ideally like to do it this weekend and have the deployment the following Monday.

**Comment by pwyborn** [comment]
Hi Said- Your ticket re deploying changes to cla_backend-deploy production. Can you give me a window of when you would like this to be done please (over weekend)?

**Comment by said-moj** [comment]
Have confirmed the following over slack:
1. I'll do the upgrade work on Sunday (our app is not used on Sundays)

2. Paul will do template-deployment deployment before 8AM on Monday and i'll drop you a link to the PR as soon as I have it

**Comment by pwyborn** [comment]
Said  9:43 AM Friday 17/04
Sorry I should clarify:
1. I'll do the upgrade work on sunday (our app is not used on sundays)
2. You will do template-deployment before 8AM on Monday(didn't think cloud platforms worked over the weekend, i'll drop you a link to the PR as soon as I have it)

Said  10:15 AM Friday 17/04
hey paul, if I did need you on a weekend would you be available, my assumption was that cloud platforms don't work on weekends

paulwyborn  10:21 AM Friday 17/04
Hi Said - no we do not work at the weekends. I was thinking if you wanted it run 5 or something this evening.
Just checking with Anthony Bishop that it is ok for me to run Monday morning - as we no longer support template-deploy - but think it is ok

Said  10:21 AM Friday 17/04
Cool, I will stick with you running on Monday morning please

paulwyborn  10:23 AM Friday 17/04
Just checking - is it the changes you made to cla_backend-deploy (some 21 days ago)  that I am running?

Said  10:23 AM Friday 17/04
No, I will create a PR and drop you the link here
10:23
it's hostname change which I don't know yet

paulwyborn  10:24 AM Friday 17/04
But it is changes to cla_backend-deploy rather than the cla_backend app?
10:26
Reason I am asking is because changes to the cla_backend app can be run from the jenkins jobs
https://ci.service.dsd.io/view/CLA/job/BUILD-cla_backend/

Said  10:26 AM Friday 17/04
yep cla_backend-deploy

paulwyborn  10:26 AM Friday 17/04
Ah ok - no problem

paulwyborn  12:58 PM Friday 17/04
So 7:30 on Monday morning it is ( will need to set my alarm)

Said  8:42 PM  Sunday 19/04
Hi Paul.
I have completed the upgrade work and no longer need you to deploy those template deploy changes for me.
Don't forget to disable your alarm and get a few extra winks

paulwyborn  8:03 AM Monday 20/04
Thanks Said. Did see this last night (and got my few extra winks)
