### ISSUE TITLE
Create a lightweight docker image for CircleCI

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1787]
The instructions in our [user guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/using-circleci-for-continuous-deployment.html#continuous-deployment-of-an-application-using-circleci-and-helm) for setting up CircleCI depend on this [ecr image] which is an abandoned branch of our main [tools image].

We need a properly-maintained docker image, ideally as lightweight as possible, that teams can use in their CI/CD jobs.

Requires guidance. Guidance should make clear than and variation from our image is not supported.

[ecr image]: http://754256621582.dkr.ecr.eu-west-2.amazonaws.com/cloud-platform/tools:circleci
[user guide]: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/use-circleci-to-upgrade-app.html#continuous-deployment-of-an-application-using-circleci-and-helm
[tools image]: https://github.com/ministryofjustice/cloud-platform-tools-image

**Comment by AntonyBishop** [comment]
We have taken the opinion that we do not want to create an image that we would need to support for a tool that we do not use ourselves. Users are much better placed to confirm what they need. We have no evidence to suggest that teams need this.

If feedback suggests otherwise we can revisit.

In the interim we will review our documentation.
