### ISSUE TITLE
Delete unused Security Groups

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1917]
We have identified a number of unused security groups.

These should be deleted.

**Comment by imran-awan1** [comment]
As disscussed in planning, this ticket comes under the following ticket

Detect and delete "leftover" AWS resources that are not identifiable in infrastructure code

https://app.zenhub.com/workspace/o/ministryofjustice/cloud-platform/issues/1929

**Comment by digitalronin** [comment]
That script looks like a very good start. The way it's determining "unused" is specific to security groups though, so we'd need to do a bit of work to extend and/or generalise it to have a different understanding of which resources we consider to be "orphaned"

https://github.com/ministryofjustice/cloud-platform-helm-charts/blob/3b5dea821fa071a6d9357eb71f31e061b29ea61f/report-unused-sg/files/unused-sgs.go#L68

**Comment by imran-awan1** [comment]
Yes agreed. The current logic is very specific to singling out unused security groups. So ideally would need to extend to add further logic to dig out any general un-used resource. Cross referencing the terraform state vs actual or using tags have been discussed so far.

**Comment by mogaal** [comment]
IMHO we should consider orphaned resources as everything not defined as a code. In technical words: everything that is not under these two S3 buckets: _cloud-platform-terraform-state_ and _cloud-platform-kops-state_. This represents all resources in our infrastructure and if something is not listed there: 1) was created manually 2) Orphan due to multiple reasons (failed destroying, someone deleted the workspace with `-force`, etc)

@imran-awan1 maybe you can update the script to look for keys called `security_groups` (all security groups resources in terraform have this key name) within these buckets I mentioned above? Doing so it will allow us to benefit from what you already did instead of replacing it with the future work on https://github.com/ministryofjustice/cloud-platform/issues/1929 . If you do in this way (parsing TF states) we can even carry on building on the top of what you already did.

**Comment by imran-awan1** [comment]
Good suggestion @mogaal in using keys. This seems realistically possible to add to the script. Will look into the 'security_group' key.

**Comment by AntonyBishop** [comment]
Will be covered by #1929 which covers "all" AWS resources.
