### ISSUE TITLE
Check that our docker images are up to date

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1927]
## Background

We should add a check to our "How out of date are we?" apps for docker images

## Proposed user journey

We can check the current status of our docker image versions via the HOODAW app and can then take the appropriate action.

## Approach

- Determine how we check and compare image versions
- Add to the HOODAW app

## Definition of done

- [ ] Docker image checks added to HOODAW app

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by digitalronin** [comment]
Most, if not all, of the components we care about are installed via Helm. So, if the docker images which are running are not the latest versions, that will be because the helm chart we use does not use the latest docker images.

This means that, even if we create a report that tells us we are using an old version of a given docker image, in practice we wouldn't be able to do anything about that.

We already report, in HOODAW, whether or not we're using a recent version of each helm chart, so this ticket is unnecessary.
