### ISSUE TITLE
Detect and delete hosted zones which are no longer required

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1933]
Automate process to detect and delete hosted zones which are no longer required.

**Comment by mogaal** [comment]
The idea would be to match the environment repo in terraform state against what we have within AWS Route53. Also, we should include what we have within the terraform state we use to create test clusters (because they also created Route53 entries).

This ticket is very much related to https://github.com/ministryofjustice/cloud-platform/issues/1929, which is trying to solve similar problem

**Comment by vijay-veeranki** [comment]
This work David/Imran did, cover the detecting route-53 zone comparing the terraform state file.
https://github.com/ministryofjustice/cloud-platform-report-orphaned-resources

https://how-out-of-date-are-we.apps.live-1.cloud-platform.service.justice.gov.uk/orphaned_resources


Need separate tickets deleting individual aws services/resources from the below list
https://how-out-of-date-are-we.apps.live-1.cloud-platform.service.justice.gov.uk/orphaned_resources

https://mojdt.slack.com/archives/C514ETYJX/p1599657096397300
