### ISSUE TITLE
User in #ask-cloud-platform asking how he can use pushgateway with Prometheus

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#1938]
Explore how can we offer pushgateway to users, it is especially useful for batch jobs.

**Comment by digitalronin** [comment]
This came up again, today: https://mojdt.slack.com/archives/C57UPMZLY/p1597409957434600

**Comment by mogaal** [comment]
And again https://mojdt.slack.com/archives/C57UPMZLY/p1605089276487900

**Comment by poornima-krishnasamy** [comment]
A previous workaround: https://github.com/ministryofjustice/cloud-platform-terraform-pushgateway

**Comment by jasonBirchall** [comment]
Requirement came up for prom gateway.
https://mojdt.slack.com/archives/C57UPMZLY/p1605544167068700

**Comment by poornima-krishnasamy** [comment]
https://prometheus.io/docs/practices/pushing/#when-to-use-the-pushgateway.

Should I be using the Pushgateway?
We only recommend using the Pushgateway in certain limited cases. There are several pitfalls when blindly using the Pushgateway instead of Prometheus's usual pull model for general metrics collection:

When monitoring multiple instances through a single Pushgateway, the Pushgateway becomes both a single point of failure and a potential bottleneck.
You lose Prometheus's automatic instance health monitoring via the up metric (generated on every scrape).
The Pushgateway never forgets series pushed to it and will expose them to Prometheus forever unless those series are manually deleted via the Pushgateway's API.
