### ISSUE TITLE
Pingdom Slack integration for Court Data Adaptor

### ISSUE THREAD

**Issue by mpw5** [ministryofjustice/cloud-platform#1948]
## Service name

laa-court-data-adaptor

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Needed so that the team is notified if the service is unavailable.

## Problem description

As per [this](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-pingdom-checks.html#adding-slack-notification) guidance, please can you create an integration for sending Pingdom alerts to a slack channel.

This will be used for alerts from three environements (dev, uat and production).

Team: LAA Crime Apps
Service: laa-court-data-adaptor
Channel: #laa-court-data-adaptor-dev

## Contact person

Mark Whitaker - slack: mark.whitaker | email: mark.whitaker@digital.justice.gov.uk

**Comment by pwyborn** [comment]
paulwyborn  08/06/2020 10:06 AM
Hi Mark - looking at your ticket for pingdom integration with slack channel -#laa-court-data-adaptor-dev.
Have you created this channel yet please?
If you have - can you open up the permissions to allow us to see (so that I can create the webhook please?

paulwyborn  08/06/2020 10:24 AM
It’s ok thanks Mark - Joel has invited me to the channel

Mark Whitaker: 08/06/2020 10:32 AM
Thanks Paul. Sorry about that, didn't realise that the channel was private... Let me know if you need me to do anything else

paulwyborn  08/06/2020 11:23 AM
Hi Mark - do you want to see if this integration (104018) works for you ok please?
https://my.pingdom.com/integrations/settings#integration=104018
Thanks (edited)

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-environments/pull/2515/files refers
