### ISSUE TITLE
Request for new sub domain of service.justice.gov.uk

### ISSUE THREAD

**Issue by mattempty** [ministryofjustice/cloud-platform#2076]
## Service name

MoJ Online product page (Form Builder Product Page)

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

We are changing the name of our service offering to MoJ Online and require a matching URL.

## Problem description

We would like our product pages have the following URL **moj-online.service.justice.gov.uk**. 
The current URL is formbuilder-product-page.apps.live-1.cloud-platform.service.justice.gov.uk

## Contact person

Matt Tei
slack @matttei
matt.tei@digital.justice.gov.uk

**Comment by mattempty** [comment]
Could I get an update on this request?

**Comment by mtrbls** [comment]
Hi @mattempty 

In order to change your URL, you would need to create a custom domain first.
Please follow the documentation [here](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/custom-domain-cert.html#defining-the-dns-zone) and [here](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/route53-zone.html#creating-a-route-53-hosted-zone).

At that point we would be able to do the last bit, which is the DNS delegation.

If you encounter any issues, please let us know.

**Comment by mattempty** [comment]
Thanks @mtrbls I've raised the PR.

**Comment by mtrbls** [comment]
Approved. 
Once it's merged and applied by the pipeline, I'll be able to do the last bit

**Comment by mtrbls** [comment]
All done @mattempty
