### ISSUE TITLE
KubeletTooManyPods

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2120]
https://mojdt.slack.com/archives/C8QR5FQRX/p1595730914004200

[FIRING:1] :warning: KubeletTooManyPods
Alert: Kubelet 'ip.eu-west-2.compute.internal' is running at 95.45% of its Pod capacity.
     Details:
      - alertname: KubeletTooManyPods
      - clusterName: live-1
      - prometheus: monitoring/prometheus-operator-prometheus
      - severity: warning
     
     -----

**Comment by digitalronin** [comment]
We may be able to do this by changing the number of retained completed cron jobs to 1 for the whole cluster.

We need to check whether users are able to override this in their cronjob definitions.

Provided both the above are true, we can announce the change, make the change, and document how to override it.

It's also worth mentioning in the documentation that just because the cronjob has been deleted, you can still see all its logs in elasticsearch.

**Comment by vijay-veeranki** [comment]
Default setting for job history limits, need to find our if we have a change this at cluster level.
https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#jobs-history-limits

**Comment by jasonBirchall** [comment]
Silence added to alertmanager. When this ticket is complete, please remove:

**Comment by vijay-veeranki** [comment]
Updated delete-completed-jobs script to removed completed cronjobs as well, which does not have ttlSecondsAfterFinished set up.
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/maintenance/jobs/delete-completed-jobs

Also updated the user-guide
