### ISSUE TITLE
[FIRING:1] :warning: CPU-High

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2127]
https://mojdt.slack.com/archives/C8QR5FQRX/p1595927910009200

Alert: This device's CPU usage has exceeded the threshold with a value of 99.86666666666376. Instance CPU usage is dangerously high
Details:
- alertname: CPU-High
- clusterName: live-1
- prometheus: monitoring/prometheus-operator-prometheus
- severity: warning

**Comment by digitalronin** [comment]
This ticket is to figure out *why* prometheus for the active master is using so much CPU.

**Comment by vijay-veeranki** [comment]
https://mojdt.slack.com/archives/C514ETYJX/p1596630059017700

The Prometheus is not on this node(172.20.73.30), which triggered the alert here and in low-priority alerts.
The Prometheus is on ip-172-20-73-23.eu-west-2.compute.internal

May be understand what is causing the CPU high looking the the node it is causing the alerts

**Comment by pwyborn** [comment]
Additional information about the pod in question (pull request):

[add specific pod information re CPU High?Critical #41](https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/41/files)

**Comment by pwyborn** [comment]
![Screen Shot 2020-08-18 at 14.03.14.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/d4334234-b2fa-40bf-ab1a-e92ddc058352)
![Screen Shot 2020-08-18 at 14.13.58.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/0e98cb18-1469-4059-ab5b-71f9691bcd32)
![Screen Shot 2020-08-18 at 14.03.31.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/c17fa532-6185-4e78-9bc7-2248201c4503)
![Screen Shot 2020-08-18 at 14.15.13.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/cb1bbb27-04b7-4983-9027-87f215f79e6c)
![Screen Shot 2020-08-18 at 14.02.31.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/861900e2-5043-4235-a2a2-ceadbe25f8bf)
![Screen Shot 2020-08-18 at 14.19.17.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/0b51739f-594e-4f33-a0c2-0ff36c3a27e1)

Kibana Query:

https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2020-08-01T00:00:00.000Z',to:now))&_a=(columns:!('@timestamp',_HOSTNAME,_CMDLINE,MESSAGE),filters:!(),index:d1d23280-fc8e-11e9-a859-bbe630739c91,interval:h,query:(language:kuery,query:'_HOSTNAME:%20%22ip-172-20-73-30%22'),sort:!(!('@timestamp',desc)))


![Screen Shot 2020-08-18 at 14.03.53.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/1cf49c10-83ab-4aaa-8a71-db6823d844c7)
![Screen Shot 2020-08-18 at 14.26.57.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/ac66aaec-5a68-4e5d-ac62-1590f6c3df8f)

Kibana Query:
https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2020-06-01T00:00:00.000Z',to:now))&_a=(columns:!('@timestamp',_HOSTNAME,_CMDLINE,MESSAGE),filters:!(),index:d1d23280-fc8e-11e9-a859-bbe630739c91,interval:h,query:(language:kuery,query:'_HOSTNAME:%20%22ip-172-20-110-88%22'),sort:!(!('@timestamp',desc)))

**Comment by pwyborn** [comment]
Kibana query '_HOSTNAME: "ip-172-20-49-113" AND MESSAGE:"Error"'

**Comment by pwyborn** [comment]
**Message in #apply-dev:**
Hi Paul Wyborn (cloud-platforms) here.
We seem to be receiving a lot of messages for “Error syncing pod” “failed to “StartContainer” for “laa-apply….” in Kibana.
Would it be possible please to clear up any failing pods please?
Thanks:thank-you:

paulwyborn Today at 4:14 PM
Hi Paul Wyborn (cloud-platforms) here.
We seem to be receiving a lot of messages for “Error syncing pod” “failed to “StartContainer” for “laa-apply….” in Kibana.
Would it be possible please to clear up any failing pods please?
Thanks:thank-you:
7 replies

Mark Whitaker  1 hour ago
Thanks for pointing this out. I’ll take a look now

paulwyborn  1 hour ago
Ah - thanks @Mark Whitaker (edited) 

Will Clarke  45 minutes ago
@Mark Whitaker I think these may relate to orphaned pods from the helm/tiller upgrade. There are some postgres pods listed that don't have associated deployments

Mark Whitaker  38 minutes ago
I’ve deleted anything that was in a failed state, hopefully that clears up the errors

paulwyborn  37 minutes ago
ok - thanks @Mark Whitaker :+1:

Mark Whitaker  37 minutes ago
@Will Clarke I deleted the postgres pods using kubectl delete statefulset ...

Will Clarke  36 minutes ago
thanks :+1:

**Message to laa-court-data-ui (Joel):**
Hi Joel (how are you)? Are you anything to do with “laa-court…..“?
4:45
If you are:
We seem to be receiving a lot of messages for “Error syncing pod” “failed to “StartContainer” for “laa-court….” in Kibana.
Would it be possible please for someone to clear up any failing pods please?
Thanks:thank-you: (edited) 
4:46
Or is there somewhere I should message (slack channel)?

jsugarman  4:47 PM
hi paul, is it laa-court-data-ui or laa-court-data-adaptor? (edited) 

paulwyborn  4:48 PM
Ah - think it’s laa-court-data-ui
4:48
Your adaptor? (edited) 

jsugarman  4:49 PM
I work on the UI. @Arlston Fernandes works on the adaptor. he just messaged me to say they have changed something - probably causing the problem

paulwyborn  4:53 PM
My Kibana query “_HOSTNAME: “ip-172-20” AND MESSAGE:“Error” AND MESSAGE:“laa-court-data-ui” - seems to have quite a lot since 20th July (edited) 

jsugarman  4:54 PM
the pods are crashlooping - it think it is some dependency updates that went in yesterday

paulwyborn  4:56 PM
Actually forget my 20th July (more recent than that)

jsugarman  4:57 PM
[10] ! Unable to load application: NameError: uninitialized constant CourtDataAdaptor::Errors
Did you mean?  Errno
bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
NameError: uninitialized constant CourtDataAdaptor::Errors
4:57
this looks like the cause for pods crash looping
5:02
working on a fix. i think i have it (edited) 

paulwyborn  5:08 PM
Ah - thanks:+1:

**Comment by pwyborn** [comment]
jsugarman  5:13 PM
yeah that fixed it - or the crashlooping at least - will deploy to all envs now
jsugarmanjsugarman
#255 Add dependency to controller
What
Add dependency to controller
Why
Not having this is causing on pod start up
Unable to load application: NameError: uninitialized constant CourtDataAdaptor::Errors
Did you mean?  Errno
bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
NameError: uninitialized constant CourtDataAdaptor::Errors
Did you mean?  Errno
Show more
Reviewers
@kmahern
<https://github.com/ministryofjustice/laa-court-data-ui|ministryofjustice/laa-court-data-ui>ministryofjustice/laa-court-data-ui | Today at 5:05 PM | Added by GitHub

**Comment by will** [comment]
The chatlogs have @ names, and github notifies people with those names (like me) when you paste them in

**Comment by pwyborn** [comment]
Update READme
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/45
