### ISSUE TITLE
Upgrade EKS to 1.17.x

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2284]

**Comment by poornima-krishnasamy** [comment]
Upgrade EKS cluster to 1.17.9 (currently available)
https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-release-announcement/
https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html

NOTE:
Faced pods getting re-created because f the default psp eks-priviledged. We dont have that in manager cluster. If the upgrade has issues in recreating the pods, add the eks.priviledged psp back, delete all the pods and it should comeback.

Update kube-proxy
Update cluster autoscaler - to 1.0.3 and repository to 
```data "helm_repository" "stable" {
  name = "autoscaler"
  url  = "https://kubernetes.github.io/autoscaler"
}```

https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler-chart/Chart.yaml#L20
