### ISSUE TITLE
HMCTS Form Finder Back office Deployment not working

### ISSUE THREAD

**Issue by rohanssalunkhe** [ministryofjustice/cloud-platform#229]
## Service name
HMCTS FormFinder back office 

## Service environment

- Dev / Development
- Staging
- Prod / Production

## Impact on the service

We can not deploy required changes to Formfinder back office. 

## Problem description

Deployment on Formfinder back office is not working. Tried on Dev which is failing (Hav not tried on Staging or prod)

## Contact person
Rohan Salunkhe

**Comment by nayoa** [comment]
Jenkins deployment failed due to using Fabric version 2.1.2. Fabric have specified that they have removed the fabric.colors module in version 2. The requirements-deploy.txt has been adjusted to only use the fabric version 1.10.1 for now. This is a temporary fix and the real solution would be to remove the fabric.colors module in the fabfile.py. 

www.fabfile.org/upgrading.html

Jenkins deployment (failed) - https://ci.service.dsd.io/view/HMCTS%20Form%20Finder%20back%20office/job/DEPLOY-hmcts-form-finder-back-office/186/console

(passed) - https://ci.service.dsd.io/view/HMCTS%20Form%20Finder%20back%20office/job/DEPLOY-hmcts-form-finder-back-office/192/console

PR - https://github.com/ministryofjustice/hmcts-form-finder-back-office-deploy/commit/c8a2ad700369702fd13c5c6ede141ee747a5fa96 - The typo has been removed from master.
