### ISSUE TITLE
New Alert Manager receiver (hmpps CFO)

### ISSUE THREAD

**Issue by mattops** [ministryofjustice/cloud-platform#2328]
Please can you set up an new Alert Manger receiver so that alert messages can be sent to:

#hmpps-cfo-dms-alerts  (private channel).

**Comment by vijay-veeranki** [comment]
Hi @mattops i am unable to add a new webhook to workspace for #hmpps-cfo-dms-alerts (private channel).
I can only see the attached related to hmpps-cfo. I think it is because the channel is private.

<img width="715" alt="Screen Shot 2020-09-15 at 14 00 17" src="https://user-images.githubusercontent.com/46675900/93213542-e38d6300-f75b-11ea-81e0-25150f227784.png">

**Comment by vijay-veeranki** [comment]
severity = "hmpps-cfo-dms"
    channel  = "#hmpps-cfo-dms-alerts"

**Comment by vijay-veeranki** [comment]
Applied

https://alertmanager.cloud-platform.service.justice.gov.uk/#/status
