### ISSUE TITLE
Upgrade default ingress controller, when no ingress is using this ingress controller

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#2399]
This is related to [2339](https://github.com/ministryofjustice/cloud-platform/issues/2339)

There is a down time while upgrading our default ingress controller.
https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx#migrating-from-stablenginx-ingress

To avoid downtime.

Steps: 

1) Create second Ingress controller
2) Create second ingress for all ingress using default ingress controller and change 
their name and ingress class to use second ingress controller
3) Change all the txt records created by external-dns to point to new ingress name.
4) external-dns will trigger and update the new NLB information for the A records in the route53 zone
**5) Upgrade default Ingress controller**
6) Change all the txt records created by external-dns to point to old ingress name.
7) external-dns will trigger and update the old NLB information for the A records in the route53 zone
8) Delete new ingress created
9) Delete new ingress controller

Upgrade default Ingress controller.

prerequisite:
1) Second ingress controller is created successfully
2) Create second ingress for all ingress using default ingress controller and change 
their name and ingress class to use second ingress controller
3) Redirect DNS traffic from the old controller to the new controller

Approach:

Make sure no ingress is using default ingress-controller, by now all the traffic should be re-directed to new-ingress controller.

Upgrade default-ingress controller:

Use the latest version.

This is the PR for the work on 2238, we need to disable mod-security and consider changes on current ingress-controller.
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/pull/5
Apply it to live-1

**Comment by poornima-krishnasamy** [comment]
Testing scenarios:

Why Downtime:
1. Default ingress controller k8s-artifacts-prod/ingress-nginx/controller - v0.34.1 enact fast shutdown when restarting or redeploying pods which result in a rise in HTTP 50x responses during pod termination. 
More details on kubernetes signal TERM and QUIT and how nginx controller handles them:
https://medium.com/codecademy-engineering/kubernetes-nginx-and-zero-downtime-in-production-2c910c6a5ed8

2. Migrating to new helm chart: The official helm chart doesnot handle reason 1 and 
because it is deploys a new service and hence a new load balancer. Hence the traffic has to be shifted to point to new load balancer. 
 
Testing scenarios:
1. Check when doing the new upgrade if the service can be pointed to the old load balancer?
2. Can we keep the elastic IPs to the old ones or is it changing when the load balancer changes? Is it possible to keep the old IPs? If not, what are the places needs changing when external IPs change
3. How the default backend handles traffic on the background? 
4. Ensure the automation script will run without interruptions like local network connection, clear log info on where it quit and how to continue from where it left. e.g. run the script from any of the pod in the cluster or bastion?

**Comment by digitalronin** [comment]
Completed by https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1004
