### ISSUE TITLE
Disable local postgresql and use RDS for concourse

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2414]
RDS postgresql database is created as part of Concourse module in order to store data. But since the helm chart has ```postgresql -> enabled : true``` by default, a local postgres is created.

- Disable creating local postgresql and check RDS postgres database updates the data.
- Remove integration test which is checking for postgres pods

## Which part of the user docs does this impact

Readme Updated

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
@poornima-krishnasamy question about this one came up in refinement. Was wondering why we moved to using RDS rather than keeping the the local postgres. There are costs associated to storing this ephemeral data in an RDS. Just wondered if there was more to this?

We should definitely only have one or the other for storage. Just want to understand why we might opt for RDS over local postgres?

Grateful if you could provide some more background.

**Comment by AntonyBishop** [comment]
Aged out
