### ISSUE TITLE
Out of disk space on cla_public

### ISSUE THREAD

**Issue by sldblog** [ministryofjustice/cloud-platform#277]
## Service name

[`cla_public`](https://github.com/ministryofjustice/cla_public)

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Users of the service can see intermittent failures in form of error pages.

## Problem description

Two out of four ~~slaves~~ production EC2 instances are out of disk space:

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1       20G   19G     0 100% /
/dev/xvda1       20G   19G   42M 100% /
/dev/xvda1       20G   19G   15M 100% /
/dev/xvda1       20G   19G     0 100% /
```

Could you help, please?

📝 There is another ticket in https://github.com/ministryofjustice/cla_public-deploy/pull/64 to increase the allocated space.

## Contact person

`@David Lantos` on Slack, @sldblog on GitHub.

**Comment by sldblog** [comment]
Update: clarified the "slaves" really mean "production EC2 instances".

**Comment by pwyborn** [comment]
Hi David 
    Paul Wyborn cloud platforms here.
I am looking at your ticket re space on the instances for cla-public-prod

David - I am assuming that everything is up at the moment as far as the app goes?

I think cla-public-staging is in the same situation re space?

Therefore I intend to carry out any action on staging first.

I am assuming that any action on production needs to be out of hours?

Because of the space issue - I do not think you can simply restart the containers - but I can try on staging.

Staging instances at the moment are t2.small (prod are t2.medium).

I can therefore change the launchconfig on staging to bring up t2.medium instances (t2.large on production)
Bring up new instances (which will in effectively bring up new containers)

When they are up and running correctly, relink the elastic ip's to the new instance id (security group rules on frontend/backend)

Hope this action is ok? In summary I will carry out on staging before anything else (edited)

**Comment by sldblog** [comment]
Hi Paul, thank you for picking this up! 
> David - I am assuming that everything is up at the moment as far as the app goes?

It's up and running, but the instances that ran out of space fail to proceed on certain pages, which results in error pages for the users.

Unfortunately, there is no monitoring and the health checks don't cover the disk space. We have tickets to rectify the monitoring deficiencies.

> Therefore I intend to carry out any action on staging first.

👍 Thank you, that sounds good to me.

> I am assuming that any action on production needs to be out of hours?

For `cla_public` it's not necessary, it can be deployed in hours.

> I can therefore change the launchconfig on staging to bring up t2.medium instances (t2.large on production)

As far as I recall, these instances have EBS-only storage so upgrading their instance size might not solve this. Could we try increasing the EBS volume size, please?

I'm not sure how to do that so the filesystem on the instances also gets resized, so I opened https://github.com/ministryofjustice/cla_public-deploy/pull/64. Is that the right thing to do?

**Comment by pwyborn** [comment]
Volume changed in staging from 10g to 20g - using method in confluence page to increase Jenkins size  (took volume snapshot first https://dsdmoj.atlassian.net/wiki/spaces/PLAT/pages/565084446/Increasing+Jenkins+Disk+Space.
Confirmed with David that staging is functioning - now for production

**Comment by sldblog** [comment]
There has been an alternative fix deployed via https://github.com/ministryofjustice/hardening-formula/pull/17 and https://github.com/ministryofjustice/cla_public-deploy/pull/66.

**Comment by sldblog** [comment]
This issue seems to have happened again. Could you advise, please?

**Comment by sldblog** [comment]
I've rebooted the instances in question which has increased available space by about ~1GB. Could we look into why these servers run out of space so soon, please?

**Comment by jojuolape** [comment]
increased volume size.

**Comment by sldblog** [comment]
@jojuolape Thank you!

However, the last instance (`i-0bceb6ba62523e6c4`) still reports 20GB as available space. Could you advise, please?
