### ISSUE TITLE
FIREBREAK: Investigate Diun to inform us on out of date docker images

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2805]
## Background

See if we can utilise Diun to inform us when a new Docker image is available.
Source: https://github.com/crazy-max/diun
```
Diun is a CLI application written in Go and delivered as a single executable (and a Docker image) to receive notifications when a Docker image is updated on a Docker registry.
```

## Questions / Assumptions

- Can we send all notifications (new image announcements) to the #cloud-platform-notify
- Can we run this in the Manager cluster?
- Is this simple to install and maintain?
- How much benefit do we get from Diun?

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by razvan-moj** [comment]
is basically a cron job that looks for pods that have a diun.watch_repo: "true" annotation
```
diun-6559668c9f-rzfqp diun Fri, 09 Apr 2021 09:48:24 BST INF Found 1 image(s) to analyze provider=kubernetes
...
diun-6559668c9f-rzfqp diun Fri, 09 Apr 2021 09:48:33 BST INF Next run in 2 hours (2021-04-09 12:00:00 +0100 BST)
```
the provider bit means it queries the K8s API, lists all pods (needs a ClusterRole for that) then goes on DockerHub/ECR and checks what’s new
an example:
```
diun-6559668c9f-zzqnq diun Fri, 09 Apr 2021 09:58:12 BST INF New image found image=docker.io/negz/kuberos:7bc1e72 provider=kubernetes
diun-6559668c9f-zzqnq diun Fri, 09 Apr 2021 09:58:12 BST INF New image found image=docker.io/negz/kuberos:b031261 provider=kubernetes
...
diun-6559668c9f-zzqnq diun Fri, 09 Apr 2021 09:58:18 BST INF New image found image=docker.io/negz/kuberos:73a4bc7 provider=kubernetes
```
so on first run it stores all tags found (needs a PV otherwise it would reset on every pod delete) and 2 hours later would log if a new tag is found
Deployment can be done with just a copy/paste of the snippet in https://crazymax.dev/diun/providers/kubernetes/ (use emptyDir or EBS for the PV)
To be useful cluster-wide, it needs to accept multiple Slack channels as targets, watch https://github.com/crazy-max/diun/issues/322
Alternatively, we could create a regular sprint story to make it into a component installable by teams
