### ISSUE TITLE
AWS IAM Profile request

### ISSUE THREAD

**Issue by Obsiye** [ministryofjustice/cloud-platform#2900]
I would like to have an AWS IAM profile to access the AWS dashboard and visualise our namespace (laa-apply-for-legal-aid), if it's not too much trouble.

## Impact on the service

This is a nice to have and won't impact our service if we don't have it.

## Contact person

abdirizak.obsiye@digital.justice.gov.uk

**Comment by AntonyBishop** [comment]
Hi @Obsiye,

At the moment this type of access is not available. It may be in the future. 

So that we can better understand the need, please can you describe what it is that you are seeking to achieve and the benefits of doing so? It may be that this need an be achieve via another route?

Grateful for some further insights. Many thanks

**Comment by Obsiye** [comment]
Hi, Anthony. I understand, it was a nice to have. 

The purpose was to be able to visualise what our namespace / laa-apply-for-legal-aid looks like as a whole without having to use the CLI. This includes looking at ecr, rds, s3 and so forth. Mainly for my learning. No biggie.

**Comment by razvan-moj** [comment]
@Obsiye why we look for a solution, we do have a Cloudwatch exporter set up that brings many useful metrics into Prometheus, eg for RDS head on to https://prometheus.cloud-platform.service.justice.gov.uk/ and try a query like 
`aws_rds_database_connections_average{dbinstance_identifier="cloud-platform-zzz"}`
The autocomplete in the query field can help discover other metrics like aws_ecr_repository_image_count

**Comment by vijay-veeranki** [comment]
This will be covered by another ticket, #3453

Closing this one
