### ISSUE TITLE
Clamav virus scanner local mirror

### ISSUE THREAD

**Issue by steverendell** [ministryofjustice/cloud-platform#2908]
## Service name

Pathfinder, SOC and others

## Service environment

All

## Impact on the service

We have had problems with our clamav servers rejecting db updates with '429 - too many attempts' type errors, basically because we have 6 envs containing clamd servers all calling out to clamav.net. This results in our virus servers failing to start when recycled.

## Problem description

The pathfinder and SOC apps use clamav to scan documents before upload to a doc store. Plus other teams also use clamav I believe, which suggests we should have a local mirror. Is this something the CP team could look into ? One obvious solution is that our team could just setup a namespace and install a mirror there but maybe a more central / integrated solution would be preferable.

Info here : https://www.clamav.net/documents/private-local-mirrors

## Contact person

steve.rendell@digital.justice.gov.uk

**Comment by razvan-moj** [comment]
Hi! A generic web proxy set up for all users is not something we want to do right now because it adds a global failure point.

For your particular issue, can you please consider first one of these more narrow focused solutions:
 1. Bundle all the antivirus updates in the actual Docker image. Deploy a new release with the frequency you want antivirus updates (eg daily)
 2. Set up a single CronJob that downloads Clamav updates (option 3 in the doc you linked) and puts them in an S3 bucket; the bucket would be reachable from all namespaces. A public ACL can be used to avoid copying IAM credentials and restrict with a policy like `"Condition": {"IpAddress": {"aws:SourceIp": ""}}` the 3 addresses listed in https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/ip-filtering.html#live-1-cluster
 3. Run a single persistent clamd server that pulls updates with the frequency wanted, and set up a NetworkPolicy in its namespace that allow the others to send files to it for scanning.

Is any of those solutions feasible for your team?

**Comment by AntonyBishop** [comment]
Issue stale. Reopen if responded to.

**Comment by davidread** [comment]
@mattops has built a helm chart for ClamAV that takes approach 1:

> build a fresh up-to-date clamav image everyday - and have the deployment pull the latest image everyday via the cronjob.

See: https://github.com/ministryofjustice/hmpps-helm-charts/tree/main/charts/clamav

HT @dazoakley https://mojdt.slack.com/archives/C3F8L6XQU/p1632497377069300?thread_ts=1632490609.062300&cid=C3F8L6XQU
