### ISSUE TITLE
recreate live cluster

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#2946]
A/C:
 - get as close as possible to a complete destroy
 - ensure terraform can create a functional cluster
 - document (in runbooks) any manual steps

**Comment by poornima-krishnasamy** [comment]
Steps:
components destroy
Cluster destroy with components
Cluster created through terraform
Components applied
All namespaces restored from velero
Apply pipeline triggered

Things to check:

time each action
Is the destroy complete, if not should I destroy completely and then apply or apply from where it is left
Is it throwing any errors
Setup pingdom alert for app running on the cluster


Issues faced:
thanos bitnami - chart failed to download from the tools image
Fix: 
helm repo chart thanos missing in the tools image 
helm repo add bitnami https://charts.bitnami.com/bitnami
The OPA is the last one to apply. 

All in cluster hostzone urls is back
urls with custom domains has not come back
Fix: 
external dns couldnot access the all hostzone ?

https://github.com/ministryofjustice/cloud-platform-terraform-external-dns/blob/main/main.tf#L1-L7

domains which has *.apps.live-1.cloud-platform has invalid certificates.
By default, `live-1` cluster provides default certificates for all domains inside *.apps.clive-1.cloud-platform.justice.gov.uk. After the app has been migrated to live cluster, those domains would still be able to use the default certificate. Hence, add default certificate to have access live-1.cloud-platform domain.  CREATE Ticket

There were 7 nodes before the destroy but now there are only 5 nodes. 
Reason: clusterautoscaler

Manager cluster lost access to the ‘live’ cluster as the concourse-build-environments serviceaccount got recreated and therefore invalidating the kubeconfig stored in s3 bucket.
Fix: Raise a PR for the new kubeconfig with new token and manually applied through terraform.https://github.com/ministryofjustice/cloud-platform-concourse/pull/422

All PSPs got destroyed including aws-node PSP. But the aws-node are part of the cluster and not components. Hence, there are pods running on cluster without a valid psp with correct permissions. For some reason, if the aws-node pods got terminated, it would be able to recreate due to not having correct permissions.

Fix: Move all PSPs to the cluster folder and apply before the components are installed. PR: Merged https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1267: 

When deleting the cluster itself, the terraform throw the error

Error: error deleting Route53 Hosted Zone (Z0000087398MZYH8HX3VD): HostedZoneNotEmpty: The specified hosted zone contains non-required resource record sets  and so cannot be deleted.
	status code: 400, request id: f04b24af-2015-4d34-adc6-83d8de54ff49

https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/402dc2d15ae080f46b60967519280adebd9397eb/terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf#L112

The code has force_destroy set to true but still it wouldnot destroy.

Reason: If there is a ingress with Routing policy, the live-1 cluster re-created the A records to the live hosted zone and hence couldnot delete the hostzone.

After the reapply of the cluster and components, the user namespaces are restored using velero. The secrets created from serviceaccont are also restored. But when the apply pipeline ran, the serviceaccount doesnot map to the secret which was restored from velero. Create ticket: https://github.com/ministryofjustice/cloud-platform/issues/3054
