### ISSUE TITLE
Dry run of migration doc with a CP app

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2956]
## Background

We have created a draft migration plan for user apps - https://docs.google.com/document/d/1kU5xOvl00QXtcak-qQONstXcMAJWvTduYH4cG_IyEbc/edit?ts=60c20a79#

We will now carry out a dry run using one of our apps that we control.

This will enable us to refine the plan document.

## Approach

This should be carried out be a couple of team members.

Pick an app. Migrate the app using the migration document.

Update the plan.

## Questions / Assumptions

Which apps will be trial migration with?

## Definition of done

- [ ] Dry run of migration document
- [ ] Update document ready for use with a test user

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
I first need an application to move over. At this point in time all "regular" CP applications had been migrated. An ideal situation would be:
- Reference app
- CI/CD pipeline in GH Actions
- Migrate using the 50/50 split

**Comment by jasonBirchall** [comment]
Current status:
- Using the reference app https://github.com/ministryofjustice/cloud-platform-reference-app
- A namespace was created in live-1 https://github.com/ministryofjustice/cloud-platform-environments/tree/main/namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-migration
- A GH Action was created to deploy to live-1
- Ingress resource up and running. Reference app deployed.

- A namespace was created in live https://github.com/ministryofjustice/cloud-platform-environments/tree/main/namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-migration
- New namespace changed the repository secrets to deploy to live, however the live pipeline is using the `cluster_name` tag `live-1` instead of `live`, causing the GitHub secret to point to the wrong cluster. This is intentional to ensure the Terraform state remains unchanged. 
- After creating the `live` namespace, the `live-1` namespace has started to fail. It correlates.

What's next:
- We need to find another way to interpolate the GitHub Action secret `cluster_name`. Perhaps not using the concourse environment variable.
- Remove the skip file in live-1 and run both apps in parallel.
- Deploy to live and create a weighting policy between the two.
- Gradually progress traffic away from the live-1 deployment to live.

**Comment by jasonBirchall** [comment]
Had to add a new CLUSTER variable named `arn:aws:eks:eu-west-2:**:cluster/live` and a new variable and secret containing the new API

**Comment by jasonBirchall** [comment]
Now deployed across live and live-1 using the live-1 ingress resource

**Comment by jasonBirchall** [comment]
Notes made on the document and followup tickets to be created.

**Comment by jasonBirchall** [comment]
Putting this ticket back into the pool for someone else to attempt

**Comment by poornima-krishnasamy** [comment]
I have my go at migrating an app. The below are my findings
1. serviceaccount module with github_repositories enabled to push gn secrets overwrite few variables and pointing to wrong cluster.
Created ticket to investigate: https://github.com/ministryofjustice/cloud-platform/issues/3085

2. Couldnot amend the ingress with the weighted policy in "live-1" and external-dns throw error 
```
RRSet with DNS name _external_dns.dev-pk.service.justice.gov.uk., type TXT, SetIdentifier poornima-dev-live-1 cannot be created as a non-weighted set exists with the same name and type
```
More details on the investigation on the slack thread: https://mojdt.slack.com/archives/C514ETYJX/p1626968845160900

**Comment by poornima-krishnasamy** [comment]
Putting this back to the sprint for someone else to have a go

**Comment by sablumiah** [comment]
Back in this Sprint for another team member
