### ISSUE TITLE
SPIKE: Making ingress audit information available in logs

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3035]
**Background**
We have had recent issues with our WAF blocking traffic, however service teams are unable to access the detail to understand why traffic was blocked. This is a bug in the latest version of modsec.

We are awaiting a new version that fixes this issue, but there is no clear roadmap from the developer as to when this may be available.

As a workaround it has been identified that we could add come config to ingress that would enable additional data to be made available in the logs.

Slack discussion [here](https://mojdt.slack.com/archives/C026MSZ5HRN/p1625226679039300?thread_ts=1625080484.010600&cid=C026MSZ5HRN
)

```
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecAuditEngine RelevantOnly
      SecAuditLog /var/log/nginx/error.log
```

**Approach**
1. We want to investigate if this will provide the level of data required by teams. Confirm with users if data is useful

2. Identify how much log data is pushed

3. Determine if it is appropriate to add this config globally or whether it should be enabled by service teams on a case by case basis.

**Comment by vijay-veeranki** [comment]
Following guidance from here did the spike:

https://github.com/kubernetes/ingress-nginx/issues/6438

Adding this snippet in nginx config

`
  modsecurity-snippet: |
    SecAuditLog /dev/stdout
    SecAuditLogFormat JSON
    SecRuleRemoveById 920350
    SecAuditEngine RelevantOnly
    SecAuditLogType serial
    Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
 `

and using below annotation in the ingresss:

`
  annotations:
    kubernetes.io/ingress.class: modsec01 
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine on
`

This is getting the additional information in the mod-sec logs.


Logically, each audit log entry is a single file. When serial audit logging is used, all entries will be placed within one file, but with default concurrent audit logging, one file per entry is used. Due to the value of the setting SecAuditLogType=Concurrent the ModSecurity log is stored in multiple files inside the directory /var/log/audit

Serial logging :

Serial logging is only adequate for moderate use because only one audit log entry can be written at any one time. Serial logging is fast (logs are written at the end of every transaction, all in one go) but it does not scale well. In the extreme, a web server performing full transaction logging practically processes only one request at any one time.

Real-time audit log centralization requires individual audit log entries to be deleted once they are dealt with, which is impossible to do when all alerts are stored in a single file.

The team pointed out that using Audit logs have a risk of exposing stuff which will cause a security risk.


So decided to wait for the [v1.0.0](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.0.0-beta.1) ingress-controller release, which got fix for mod-sec logs which are missing, as this version includes this [commit](https://github.com/SpiderLabs/ModSecurity-nginx/commit/e028ca43c83fd114344c34df6a8dd09eb5f34cc2).
