### ISSUE TITLE
Audit of integration test

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3359]
## Background

We need to improve the state of our integration tests. The original improvement work was paused for EKS migration. We are now ready to start working on our tests but we aren't clear on the current status of our tests.

The purpose of this story is to review the current state of play so that we can determine our priorities.

**Addresses Risk 16 and 43**

## Approach

We should review all of tests and we able to answer the following questions:
- Which tests are already converted to Go?
- Do any tests converted to go need to be revisited and why?
- Which tests are in Ruby and need to be converted to Go?
- Which tests are in Ruby and do not need to be converted to Go (i.e. specific to "Live-1" or Kops)
- What tests are we missing?

## Definition of done

- [ ] We have an up to date view on the state of our integration test
- [ ] We can use the audit to prioritise which tests to work on

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
> Which tests are already converted to Go?

The layout for our [tests written in go](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/tests/e2e) is fairly unique. We currently cover:

```
- Check daemonsets exist

- functionality of external-dns

- existance of authorised keys on a bastion node

- functionality of the modsec ingress controller

- all expected namespaces exist (i.e. monitoring etc)

- functionality of the default ingress controller

- all expected servicemonitors exist

- all expected services exist
```

**Comment by jasonBirchall** [comment]
> Do any tests converted to go need to be revisited and why?

In my opinion, there are a few things we should re-visit. I'll outline them here:

Layout and versioning
---

Currently, all Go tests are stored in a directory called `/tests`. While there's no problem with this, its module also exists in the same directory, meaning it's very difficult to version control. This leads to problems with version drift. For example, the current [main](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/tests) branch of the infrastructure repository contains 11 individual tests but the concourse pipeline only runs [8](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/reporting/jobs/live-integration-tests-go/builds/363#L619e6895:8).

My theory is that due to the nature of sub-modules and Go packages in a repository the [Dockerfile](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/tests/Dockerfile) hasn't been manually built/pushed/deployed.

I suggest we remove the Go module in the `tests` [directory](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/tests/go.mod#L1) and create a Go module at the root of the [cloud-platform-infrastructure](https://github.com/ministryofjustice/cloud-platform-infrastructure) repository. This will allow us to take advantage of GitHub semvar versioning, with release notes etc.

Carrying out the above suggestion offers the following advantages:

- we treat our infrastructure code like any other. All features and increments should have an individual unit and integration test.

- as mentioned previously, use GitHub tagging, allowing us to version correctly and create clear concise release notes.

- offer feature branches.

- automate the Dockerfile build, tag, push process. On release, GH actions can be called to create a tagged image.

- having the module exist in the root of the repository allows you to store your tests throughout the repository (enabling us to store unit tests with code) and still run Go's special command:

```bash
go test ./...
```

Some disadvantages should be mentioned:

- tagging and releasing in GitHub is a slight pain.

- the Go module won't be specific to tests. The same module would be used to execute/test/dependency manage any Go package in the infrastructure repo.

Use a layered approach to testing
---

I would like to suggest offering a layered approach to testing - using different tools. To help visualise this I split the functions of the platform offering into tiers.

tier 1 := infrastructure provisioning. Terraform and Cloud Formation code in the repository.
tier 2 := kubernetes, eks and kops.
tier 3 := cloud-platform specifics i.e. on-boarding, terraform apply pipeline, cluster creation etc.

What exists ----

(tier 1) We currently test the end-to-end infrastructure provisioning with a pipeline that creates, tests and destroys a cluster.

(tier 2) We create Ruby and Go tests to mimic the expected behaviour of components.

(tier 3) We currently don't test the speed of on-boarding, although we do unit test the CLI but this wouldn't catch dependency failures like the existence of a Terraform module when someone runs `cloud-platform environments rds create`. We have a Ruby test for the apply pipeline but this has remained dormant [since 2020](https://github.com/ministryofjustice/cloud-platform-environments/blob/main/spec/pipeline_spec.rb). 

I think there is an argument for on-boarding and apply pipeline testing to exist in other repositories, so we'll leave these for another discussion.

I think the main focus should be:
- cluster creation
- cluster divergence
- cluster destroy
- cluster node recycling

Suggestions ----

(tier 1) We should write unit tests for each Terraform layer that exists. For example, we could use the [terratest](https://github.com/gruntwork-io/terratest/blob/master/test/terraform_hello_world_example_test.go) to create a test cluster and then run [assertion tests against them](https://github.com/gruntwork-io/terratest/blob/master/test/terraform_hello_world_example_test.go). This would confirm the Terraform we've written actually works as expected.

Advantages: 

- We can add features and increments with more assurance we aren't breaking things.

- Going forward we can use a TDD approach, making testing a first class citizen on all infrastructure as code.

Disadvantages:

- We may not have the time and engineering effort to get us to this point.

- Maintaining the tests are sometimes cumbersome.

(tier 2) There are tools that we've spiked during firebreaks that enable us to run synthetic tests against Kubernetes components. One that I'd like to mention here is [kuberhealthy](https://github.com/kuberhealthy/kuberhealthy). This would allow use to other tools [recommended by other Kubernetes users](https://kubernetes.slack.com/archives/C0X2V69D0/p1637589664463300), maintained by other people, to tell us the same thing we're wasting time re-inventing.

Advantages:

- We don't have to maintain any code.

- If we choose Kuberhealthy, we could contribute to the already large community of users.

Disadvantages:

- If we choose Kuberhealthy, we have to install a controller in the cluster.

- YAML ;)

(tier 3) Anything custom to the Cloud Platform will be more unique and require custom build testing solutions. The GinkGo/Omega packages are really good for testing behaviour, so we should create them using these tools. A lot of the tooling for tier 3 is written in Ruby, but I think testing behaviour is probably more important. The underlying tools for the node recycler should be re-written in Go, but that's another story.

Advantages:

- The team will be comfortable making changes to the infrastructure tooling.

- Enables a good platform to do TDD and make testing a first class citizen.

Disadvantages:

- I think time to get to this point.

**Comment by jasonBirchall** [comment]
Layout and versioning
---

Currently, all Go tests are stored in a directory called `/tests`. While there's no problem with this, its module also exists in the same directory, meaning it's very difficult to version control. This leads to problems with version drift. For example, the current [main](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/tests) branch of the infrastructure repository contains 11 individual tests but the concourse pipeline only runs [8](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/reporting/jobs/live-integration-tests-go/builds/363#L619e6895:8).

My theory is that due to the nature of sub-modules and Go packages in a repository the [Dockerfile](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/tests/Dockerfile) hasn't been manually built/pushed/deployed.

I suggest we remove the Go module in the `tests` [directory](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/tests/go.mod#L1) and create a Go module at the root of the [cloud-platform-infrastructure](https://github.com/ministryofjustice/cloud-platform-infrastructure) repository. This will allow us to take advantage of GitHub semvar versioning, with release notes etc.

Carrying out the above suggestion offers the following advantages:

- we treat our infrastructure code like any other. All features and increments should have an individual unit and integration test.

- as mentioned previously, use GitHub tagging, allowing us to version correctly and create clear concise release notes.

- offer feature branches.

- automate the Dockerfile build, tag, push process. On release, GH actions can be called to create a tagged image.

- having the module exist in the root of the repository allows you to store your tests throughout the repository (enabling us to store unit tests with code) and still run Go's special command:

```bash
go test ./...
```

Some disadvantages should be mentioned:

- tagging and releasing in GitHub is a slight pain.

- the Go module won't be specific to tests. The same module would be used to execute/test/dependency manage any Go package in the infrastructure repo.

**Comment by jasonBirchall** [comment]
The config file idea is confusing and neglects test clusters
---

Our current Go tests require a config file passed to them. You essentially run:

```bash
go test ./... -config live.conf
```

which sets the context of your test. It checks for all things in this file, like namespaces and services.

In my opinion, this neglects anything that isn't a known cluster i.e. `live-1`, `live`. If you have a test cluster and you want to confirm namespace existence, it can't be done.

If we want to keep this structure, we should create a default config file that "standard" Cloud Platform clusters model. Anything specific to a cluster should be maintained in its own file.

**Comment by jasonBirchall** [comment]
> Which tests are in Ruby and need to be converted to Go?

Tests currently in Ruby that should be converted to Go
---

```
- functionality of cert-manager

- functionality of logging

- functionality of rbac access

- functionality of pod security policies

- existence of default certificate

- existence of concourse components

- existence of expected custom resource definitions

- exitstence of namespace annotations

- functionality of IRSA

- existence of prometheus rules

- existence of starter pack

```

Tests currently in Go:
---

```
- functionality of external-dns

- functionality of the default ingress controller

- functionality of the modsec ingress controller

- existence of authorised keys on a bastion node

- existence of daemonsets

- existence of namespaces (i.e. monitoring etc)

- existence of servicemonitors

- existence of services
```

Tests currently in Ruby:
---

```
- functionality of cert-manager

- functionality of external-dns

- functionality of the default ingress controller

- functionality of the modsec ingress controller

- functionality of KIAM

- functionality of logging

- functionality of master nodes

- functionality of rbac access

- functionality of pod security policies

- existence of services

- existence of default certificate

- existence of authorised keys on a bastion node

- existence of namespaces (i.e. monitoring etc)

- existence of concourse components

- existence of expected custom resource definitions

- existence of daemonsets

- existence of docker-registy cache

- existence of KIAM

- existence of master nodes

- exitstence of namespace annotations

- existence of prometheus rules

- existence of pod security policies

- existence of service monitors

- existence of starter pack

- other: is external dns zone clean?
```

**Comment by jasonBirchall** [comment]
> Which tests are in Ruby and do not need to be converted to Go (i.e. specific to "Live-1" or Kops)

```
- existence of KIAM

- functionality of master nodes
- 
- existence of docker-registy cache
```

**Comment by davidread** [comment]
@jasonBirchall reports that in the meeting we agreed to take these proposals (above) forward. These fall into three actions, which are something like (TBC):

* repo restructure - remove the Go module in the tests directory and create a Go module at the root of the cloud-platform-infrastructure repository
* Spike kuberhealthy
* Get rid of config file - tests run across all clusters, but tag test with the cluster that it does/doesn't run on

And then we convert remaining Ruby tests to Go.

TODO: create these to tickets
