### ISSUE TITLE
Please add my GPG key to https://github.com/ministryofjustice/ops-maintenance

### ISSUE THREAD

**Issue by isherraikmo** [ministryofjustice/cloud-platform#341]
## Service name

https://github.com/ministryofjustice/ops-maintenance

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

I need to upgrade the Postres DB version in use on tax tribunals, which will disrupt live service. We have been asked to put a maintenance page up during the upgrade, so I will need my key added to this repo so that I can create a new maintenance page for this service.

## Problem description

I need to upgrade the Postres DB version in use on tax tribunals, which will disrupt live service. We have been asked to put a maintenance page up during the upgrade, so I will need my key added to this repo so that I can create a new maintenance page for this service.
The GPG key fingerprint that needs adding is 4A323C00953F3E9B1FA557E2D5B58EF63DF3CEA3

## Contact person

Isher Singh Raikmo
Slack handle: @Isher Singh Raikmo

**Comment by lukaszraczylo** [comment]
There's no git-crypt in ops-maintenance repository.

**Comment by pwyborn** [comment]
Isher Singh Raikmo [9:33 AM]
Good morning @here, can somebody please look at my request for adding my GPG key to the ops-maintenance repo please?

https://github.com/ministryofjustice/cloud-platform/issues/341
isherraikmo
#341 Please add my GPG key to https://github.com/ministryofjustice/ops-maintenance
*Service name*

https://github.com/ministryofjustice/ops-maintenance

*Service environment*

☐ Dev / Development
☐ Staging
• [x ] Prod / Production
☐ Other

*Impact on the service*

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

I need to upgrade the Postres DB version in use on tax tribunals, which will disrupt live service. We have been asked to put a maintenance page up during the upgrade, so I will need my key added to this repo so that I can create a new maintenance page for this service.

*Problem description*

I need to upgrade the Postres DB version in use on tax tribunals, which will disrupt live service. We have been asked to put a maint… Show more
Labels
support team
ministryofjustice/cloud-platformAug 24thAdded by GitHub


lukasz [9:33 AM]
@Isher Singh Raikmo I’m not sure if ops maintenance is used and server is not decommissioned

Isher Singh Raikmo [9:34 AM]
@lukasz do you have something different/better instead now for maintenance pages that we could use?
the service is tax-tribunals, it’s in mojdsd if that makes a difference

lukasz [9:35 AM]
also there’s no git-crypt there

Isher Singh Raikmo [9:35 AM]
there appears to be
https://github.com/ministryofjustice/ops-maintenance/blob/master/.gitattributes
https://github.com/ministryofjustice/ops-maintenance/blob/master/README.md#pre-requisite---git-crypt

lukasz [9:38 AM]
```(pvb2) @ 9:34am [nvm@Lukaszs-MacBook-Pro] ~/Documents/projects/projects-work/ops-maintenance git:(master)$ git-crypt add-gpg-user 3DF3CEA3
git-crypt: Error: Unable to open key file - have you unlocked/initialized this repository yet?
(pvb2) @ 9:34am [nvm@Lukaszs-MacBook-Pro] ~/Documents/projects/projects-work/ops-maintenance git:(master)$ git-crypt unlock
Error: no GPG secret key available to unlock this repository.
To unlock with a shared symmetric key instead, specify the path to the symmetric key as an argument to 'git-crypt unlock'.
(pvb2) @ 9:38am [nvm@Lukaszs-MacBook-Pro] ~/Documents/projects/projects-work/ops-maintenance git:(master)$```
so I don’t have my key there - cc @paulwyborn
on that note i’m quite sure we don’t use that repo anymore

Isher Singh Raikmo [10:00 AM]
@lukasz ok, thanks. do we have something different instead which we do use now instead of this?

lukasz [10:01 AM]
we haven’t used maintenance server / pages for 2 years+

paulwyborn [10:14 AM]
@lukasz @Isher Singh Raikmo - I don’t have my key on ops-maintenance either

paulwyborn [10:26 AM]
@Isher Singh Raikmo - you may want to set up your own version of (or something similar to) this? Needs though to be separate from ours. https://dsdmoj.atlassian.net/wiki/spaces/PLAT/pages/684359870/Maintenance+Mode

**Comment by pwyborn** [comment]
Advice given re ops-maintenance page (no-one has access to ops-maintenance - no longer used)
