### ISSUE TITLE
What are the things we need to do to make Flux available to our users

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3476]
## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
https://fluxcd.io/

**Comment by pwyborn** [comment]
https://mojdt.slack.com/archives/C514ETYJX/p1644249343726929?thread_ts=1644244474.740159&cid=C514ETYJX

**Comment by pwyborn** [comment]
https://github.com/fluxcd/flux2/discussions/431
At this moment we do not plan to maintain a Helm chart in the foreseeable future.

Helm charts tend to be maintenance (and support) heavy, and in combination with the limitations around rolling out Custom Resource Definitions it is not a perfect fit for any of the GitOps Toolkit components at present. Introducing a way to generate the Hem chart

**Comment by pwyborn** [comment]
Background info:

- Flux is a Gitops tool for keeping Kubernetes clusters in sync with sources of configuration (source of truth).

- The source of truth being Git - being compared to what is actually in the cluster.
Flux detects any drift between them

- Rather than a pipeline being run outside of the cluster, flux runs inside the cluster:
The advantage being that you do not need to export credentials and secrets outside of the cluster.

- Flux checks for new Git commits and any manual manifest changes in the repository:
It takes these and applies them to the cluster.

- Continuous delivery has therefore gone from push commits from the external pipeline - to Gitops pull daemon within the cluster.
- Flux consists of controllers. Controllers can be written in GO.

- Installation of Flux:
Add CRDs (custom resource definitions)
Add controllers
Create bootstrap repository
Add Git credentials to the cluster
Configure flux to reconcile from the Git repository.

- To bootstrap Flux:
Git repositories need to contain the manifests for the controllers - they are deploying itself
Therefore need sources in both the Git repository and the cluster.

**Comment by pwyborn** [comment]
![Screen Shot 2022-02-14 at 11.05.39.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/1a06769b-db23-4912-a5d2-409e672f3fb6)

**Comment by poornima-krishnasamy** [comment]
https://docs.google.com/document/d/1wTJ0RCItIAcXus3tbrGG47-MfSt5WOgUfhkLsmlC10k/edit?usp=sharing

**Comment by poornima-krishnasamy** [comment]
Closing the ticket as a follow up ticket has been created as a firebreak action.
