### ISSUE TITLE
Git-crypt -Investigate removing gpgkeys for leavers from repos

### ISSUE THREAD

**Issue by pwyborn** [ministryofjustice/cloud-platform#357]
Another area that I know needs to be looked at is git-crypt gpgkeys - I am sure that Niall etc are left on a lot of the apps. Sure I heard that it is not easy to remove these keys - To investigate - whether (at the very least there could be a process for gpg keys removal)

**Comment by pwyborn** [comment]
Background
Another area that I know needs to be looked at is git-crypt gpgkeys - I am sure that Niall etc are left on a lot of the apps. Sure I heard that it is not easy to remove these keys - To investigate - whether (at the very least there could be a process for gpg keys removal)

Proposed user journey
Process for removing all gpg keys for leavers on all apps

what breaks
Nothing breaks as such - old gpg keys still on repos

Definition of done
Find out if possible to manually remove these gpg keys from deploy repos
Investigate process to automate this for each deploy repos

stretch
Incorporate ssh-key update process (one process for all - suggestion by Lukasz)

Reference
How to write good user stories

**Comment by nayoa** [comment]
After research, it appears that there is not a command to delete a gpg user. An issue has been open on GitHub since 2015 on implementing the feature - https://github.com/AGWA/git-crypt/issues/47. However, the creator has explained that it is very difficult to implement. A bash script has been created to solve the problem. However, the script involves deleting git-crypt from the repo, then adding it back but without the user that is to be revoked. https://gist.github.com/glogiotatidis/e0ab45ed5575a9d7973390dace0552b0. This seems like a hacky method but would add an extra layer of security to repos with git-crypt.
