### ISSUE TITLE
Family mediators service can't build/deploy

### ISSUE THREAD

**Issue by zheileman** [ministryofjustice/cloud-platform#414]
## Family mediators service

URL of the service:
https://familymediators.service.justice.gov.uk/admin/

URL of the repo:
https://github.com/ministryofjustice/family-mediators-api

Deploy repo:
https://github.com/ministryofjustice/oocp-familymediators-deploy

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

The service is currently up and running, but we can't build through the Jenkins job nor deploy. We think It is probably due to outdated recipe/formula.

https://ci.service.dsd.io/view/family-mediators/

## Contact person

Jesus @ slack

**Comment by pwyborn** [comment]
paulwyborn [4:29 PM]
@jesus - your deployment should be ok now https://ci.service.dsd.io/view/family-mediators/job/family-mediators-api-deploy/52/

**Comment by pwyborn** [comment]
Done - complete

**Comment by pwyborn** [comment]
Confirmation that deploy now working - problem with build - looking into

**Comment by pwyborn** [comment]
paulwyborn [6 minutes ago] 05/10/2018
Hi @jesus - could you perhaps give it another go running the build master please (must be permissions with jenkins somewhere)?


jesus [6 minutes ago]
will do, 1 sec


jesus [4 minutes ago]
I think it's taking longer this time, might be fixed!


paulwyborn [3 minutes ago]
I added you as an admin user in Jenkins- so hopefully…….


jesus [2 minutes ago]
that's weird, because I'm able to build other jobs without being an admin, but maybe for this project is neccessary?


paulwyborn [1 minute ago]
:man-shrugging: - anyway looks your off and running


jesus [1 minute ago]
yep, that seems to do the trick! thanks for your patience in the matter!


paulwyborn [< 1 minute ago]
np

**Comment by pwyborn** [comment]
Build now working

**Comment by pwyborn** [comment]
Complete - Done
