### ISSUE TITLE
DockerHub rotation

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4334]
## Background

Operations Engineering would like to like to rotate a secret but this requires coordination with Cloud Platform to avoid downtime and impact on CI/CD.

Cloud Platform Team will rotate the secret and let Ops Eng know so that they can update their records.

Current secret is stored in the Password Manager

## Which part of the user docs does this impact

N/A

## Definition of done

- [ ] Secret rotated
- [ ] Password Manager updated

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
Regarding docker hub secret rotation.
I tested to see if we can use a token instead of using the password for the docker user and it is working well.

I think we need to use the token instead of the password of the user, so we can have a separate token for cloud-platform use, and other teams(ex: the operation engineering team) can have a different token for their needs.

This is what Docker saying regarding tokens:
Personal access tokens are linked to your Docker account and can be used in place of a password.

**Comment by vijay-veeranki** [comment]
We also need to use this token used in concourse, saved as secret in concourse to use it for pipelines
