### ISSUE TITLE
CPU-Critical work: OPA rule for limitrange

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#4490]
Look into creating an OPA rule that does not allow users to specify higher resource defaults and limits higher than values specified in the limitrange

Things to consider:

Would this stop deployments setting resources too high? 

WIll this cause higher default/limits In the NS as the limitrange would become the default values for all pods if resources are not specified in the pod manifest? 

Would specifying resources in pods become mandatory?

**Comment by poornima-krishnasamy** [comment]
As per the kubernetes documentation: https://kubernetes.io/docs/concepts/policy/limit-range/
Pod CPU/Memory default limits cannot go higher than the one set in limitRange. 
Pod CPU/Memory defaultsRequests can go higher than the one set in limitRange. This will allow different pods in the same namespace to have different defaultsRequests. So they can be scheduled on correct node with enough CPU/Memory to process. E.g. jobs which needs higher cpu/memory defaults to start

Hence, we should allow deployments with higher defaultsRequests than the one set in the limitRange.

The defaultRequest set in limitRange are generally small and hence ok to be set to pod if one not specified in pod manisfest.

WIll this cause higher default/limits In the NS as the limitrange would become the default values for all pods if resources are not specified in the pod manifest?
Thats true. If we deny setting a higher defaultRequest in pod manifest, then users tend to set the NS level higher which means all pods in that namespace are set to higher defaultRequests. This will not be useful and will cause more nodes to be spinned to satisfy the requests

After considering all reasons, I dont think a OPA rule would help in reducing/avoiding the Node CPU going Critical or new nodes getting spawned because of incorrect defaultRequests/limits.
