### ISSUE TITLE
Move cloud-platform-reports-api-key to AWS Secrets Manager

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4570]
## Background

HOODAW Frontend which is deployed in cloud-platform-reports-prod uses a API key to validate the POST requests coming from the manager cronjobs. It is part of helm chart and the values are manually applied.

## Approach
Create a secret using [secrets-manager module](https://github.com/ministryofjustice/cloud-platform-terraform-secrets-manager.git) following the guide https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/secrets/create.html and reference the kubernetes_secret in the deployment template.
## Which part of the user docs does this impact

https://github.com/ministryofjustice/cloud-platform-how-out-of-date-are-we/tree/main/cloud-platform-reports

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done
- [x] API key moved to AWS SM 
- [x] readme has been updated
- [x] user docs have been updated
- [x] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
Namespace secret created:
https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reports-prod/resources/secret.tf

Helm deployment api-key secret ref updated:
https://github.com/ministryofjustice/cloud-platform-how-out-of-date-are-we/blob/main/cloud-platform-reports/templates/deployment.yaml#L23-L25

**Comment by sj-williams** [comment]
HOODAW repo is in need of a cleanup. Had a chat with Poornima re things to consider for future work:

- both HOODAW frontend and cron jobs deployments are currently managed manually. We need to find a better way of automating deployment.

- cronjobs should be in its own repo away from the frontend deployment (as they are deployed onto manager cluster). We should create a HOODAW cron module and manage deployment via Helm Release at Components level in infra.

- frontend is deployed into live in its own namespace. We can setup a Terraform Helm release for this in order to maintain the Chart release via environments pipeline(s).
