### ISSUE TITLE
Check the current IP Prefixes allocated/Free for current live private subnets

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4796]
## Background

When doing the EKS Module upgrade, we found that there were some limits to providing IP Prefix to the ENI to provision the CNI to allocate IP addresses. Below is the error message from CNI

```“Unable to get IP address from CIDR: no free IP available in the prefix```

We need to make sure this doesn't occur when doing the 1.25 upgrade.

## Approach

Based on the current live- private Subnet on each AZ configured for the cluster, check how many IP prefixes the cluster holds, how many are free. Will this be enough when doing upgrade as the cluster expands to add more nodes to shift the workload.

The approach could be raising a ticket with AWS and ask how is this managed and how to calculate and understand that the cluster wont get starved by IP Prefix with the current setup.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jaskaransarkaria** [comment]
A potential solution to look into:

https://docs.tigera.io/calico/latest/networking/determine-best-networking#aws

**Comment by prakash-moj** [comment]
Total - 1645 NIC used as of 15th/Nov/2023

NIC Usage by service 

    RDS Service     - 764
    Elasticsearch   - 141
    Elasticcache    - 546


Total EKS worker nodes = 48 each attached with 8 IPv4 Prefixes (/28) 

Total IPs can be allocated to EKS worker nodes

48 nodes / 128 (total 8 NIC * 16) = 6144 IPs for EKS

Each node - IP Prefix - 8 * 16 = 128 IPs allocated/node / 110 containers max per node (average 50% used)

We still got 60% Free IPs available across three private subnets. However, there could be subnet fragmentation due to huge number IPs allocated for other AWS managed services.

**Comment by prakash-moj** [comment]
Additional logs from history:

`{"level":"error","ts":"2023-09-18T14:22:10.964Z","caller":"ipamd/ipamd.go:1083","msg":"Failed to allocate a private IP/Prefix addresses on ENI eni-0a8a4e49eb605c3a2: InsufficientCidrBlocks: The specified subnet does not have enough free c
idr blocks to satisfy the request.\n\tstatus code: 400, request id: bacd0e05-6233-4fec-82c6-904622cc2a78"}
{"level":"error","ts":"2023-09-18T14:22:11.272Z","caller":"ipamd/ipamd.go:707","msg":"Unable to attach IPs/Prefixes for the ENI, subnet doesn't seem to have enough IPs/Prefixes. Consider using new subnet or carve a reserved range using cr
eate-subnet-cidr-reservation"}
{"level":"debug","ts":"2023-09-18T14:22:21.275Z","caller":"ipamd/ipamd.go:707","msg":"Recently we had InsufficientCidr error hence will wait for 2m0s before retrying"}`

**Comment by prakash-moj** [comment]
We might see the CIDR errors during upgrade due to subnet defragmentation during 1.25 upgrade process intermittently. 

I think we definitely need to extend / add more private subnet which requires change in all existing security groups attached with various AWS services such as RDS etc. The scope of the work might be slightly bigger so we can try to tackle this after 1.25 upgrade.

**Comment by prakash-moj** [comment]
Extending the subnet work would be carried through separate tickets

https://github.com/ministryofjustice/cloud-platform/issues/4780

https://github.com/ministryofjustice/cloud-platform/issues?q=is%3Aissue+is%3Aopen+spike+ip
