### ISSUE TITLE
Add a Github Action to check deletion_protection = false when ecr is removed

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4828]
## Background

When a user raise a PR to remove ECR or namespace along with the ECR resources, the destroy pipeline runs and does the destroy of terraform resoruces followed by the kubernetes destroy. But if the ECR to be deleted contain images, the destroy fails with

```
The repository in registry with id '754256621582' cannot be deleted because it still contains images
```

## Proposed user journey

There are instructions that user has to specify [deletion_protection = false` in first PR before raising PR to delete the ECR. But it is very easy to miss. If that is missed, Cloud Platform team has to manually go and delete all the images and re-run the pipeline.

## Approach

Create a github action which will look for PRs which has ecr resource to be deleted and add a comment in that PR to 
"make sure the deletion_protection is set to false"

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] github action added to cloud-platform-environments to detect ecr resource deletion 
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by tom-j-smith** [comment]
We will also want to add the following checks:
- delete protection on ecr set to false
- ecr does not contain images
- delete protection is set to false on other resources e.g. rds, s3 buckets, etc

**Comment by poornima-krishnasamy** [comment]
The alternative is to let the cli update the terraform code in the PR to have deletion_protection = false, do a terraform apply and then perform the terraform destroy. The cli way has to ensure it only updates the deletion_protection of which ever module is getting destroyed in the PR.

**Comment by AafAnsari** [comment]
The current scope of this story is to detect if an ecr resource is being deleted in the user’s PR and to inform the user by commenting on their PR.

There are number of ways the ecr resource can get deleted. To list a few
- User deletes the `ecr.tf` file itself
- User comments out the module. This can be commenting either the whole or partial file which can trigger the ecr deletion.
- User has ecr module added in some other tf file and not in `ecr.tf` and then comments/removes the ecr module from it.
- User updates the `team_name` or `repo_name` that triggers `ecr.tf`  deletion(this is a bug and need to be fixed in another story)

I have narrowed down the scope of this PR to look at the deleted files specifically named as `ecr.*\.tf` as this covers all of the ecr modules in [environments repo](https://github.com/ministryofjustice/cloud-platform-environments) and fail the action if `deletion_protection = true`. This will enforce the rule to set the `deletion_protection = false` before user tries to delete the ecr.
