### ISSUE TITLE
Upgrade nginx-ingress chart

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#493]
## Approach

Upgrade the chart to use the latest version on all clusters.

## Definition of done

- [x] nginx-ingress in live-0 is updated
- [x] terraform component plan is clean

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
Current chart version on test-a and live-0 - 0.29
Latest version - 0.31

Its possible to upgrade to version 0.30 however the following error occurs when trying to go to  0.31. 
`helm_release.nginx_ingress: rpc error: code = Unknown desc = Service "nginx-ingress-controller" is invalid: spec.clusterIP: Invalid value: "": field is immutable`

Its possible to taint/destroy current version and reinstall latest however this occurs additional downtime as opposed to an inline upgrade. There is a change on 0.31 that requires this reinstall and no easy work around is available due to us using helm_release via terraform as opposed to helm directly.

There is also a need to do a destroy - reinstall due to wanted to use the latest chart as opposed to it being versioned, however terraform does not see this as a change when 'version' is removed from the tf file. 

So its been agreed to hold off from completing this ticket till 0.32 get released so we can test inline upgrades 0.31+ and do a once destroy-reinstall for live-0.

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/137
