### ISSUE TITLE
Copy all elasticsearch ALERTS to opensearch

### ISSUE THREAD

**Issue by jaskaransarkaria** [ministryofjustice/cloud-platform#5120]
## Background

Copy the ALERTS over to the new opensearch cluster, so when users migrate they don't lose any of their ALERTS

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by timckt** [comment]
Discussed with Jas and Poornima, this ticket should be internal alert focus, and create a new [ticket](https://github.com/orgs/ministryofjustice/projects/65/views/8?sliceBy%5Bvalue%5D=Move+user+application+logs+to+OpenSearch+cluster&pane=issue&itemId=59949061) for user's alert migration.

**Comment by timckt** [comment]
We need to revert the change because there is an error when applying the change.
```
│ Error: elastic: Error 405 (Method Not Allowed)
│ 
│   with elasticsearch_opensearch_destination.cloud_platform_alerts,
│   on app-opensearch-alerts.tf line 1, in resource "elasticsearch_opensearch_destination" "cloud_platform_alerts":
│    1: resource "elasticsearch_opensearch_destination" "cloud_platform_alerts" {
│ 
╵
```
This maybe related to that destinations will be deprecated going forward in Opensearch from Opensearch Destinations [Page](https://app-logs.cloud-platform.service.justice.gov.uk/_dashboards/app/alerting#/destinations?from=0&search=&size=20&sortDirection=desc&sortField=name&type=ALL).

Also we also need to use [new resource block](https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs/resources/channel_configuration) `opensearch_channel_configuration` for Opensearch and it involves the testing of new terraform [opensearch provider](https://registry.terraform.io/providers/opensearch-project/opensearch/latest).

**Comment by timckt** [comment]
Our ES rules are copied to OS and are now disbaled.

Will enable it after OS migration.

Relates to ministryofjustice/cloud-platform#5515
