### ISSUE TITLE
MPS live system not available to some users

### ISSUE THREAD

**Issue by pazinlondon** [ministryofjustice/cloud-platform#526]
## Service name
Moving People Safely

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ x] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.
Healthcare users at HMP Durham (who use the G4S network) are unable to access the system to complete their work

## Problem description

Users are able to use MoJ signon fine but when they are transferred to the MPS application (https://personescortrecord.service.justice.gov.uk) they get the following error message
Can't connect securely to this page

This might be because the site uses outdated or unsafe TLS Security Settings. If this is keeps happening to contact the websites owners.

Checked and the site certificate is showing as valid (but expires 10th December). Any ideas how to resolve?

 ##Contact person

@psmiddy, paul.smith@digital.justice.gov.uk

**Comment by lukaszraczylo** [comment]
As per Paul's message few minutes ago:
"Hi, we believe the problem at HMP Durham may have been caused by the NHS migrating to a new IP range for their N3 gateway. Could someone add the following new range to the MPS production whitelist urgently and let me know when it’s done please? xxx. 
There should be a support request put in this morning @razvan-moj  was investigating. Thanks"

Limit of entries in SG has been reached, I will need the old g4s IPs ( don't post them here, just message me privately on Slack ) to remove the old access before adding new ones.

**Comment by lukaszraczylo** [comment]
As this request seem to be quite urgent I've created a separate security group for that vpc ( mps-whitelist ), with mentioned records and daisy chained it to the existing security group ( sg-bfdd87db ). Waiting for Slack feedback in the morning.

**Comment by lukaszraczylo** [comment]
I've created separate security group ( mps-whitelist ) which I've added required records to and applied it to the ELB together with testing the fix on my private IP.
