### ISSUE TITLE
Add create-blue-green-deployment permissions to RDS IRSA

### ISSUE THREAD

**Issue by tom-j-smith** [ministryofjustice/cloud-platform#5282]
## Background

Suggested by David Read in the ask channel, they are keen to use RDS Blue Green deployment to upgrade their RDS database. They use AWS API commands including aws rds create-blue-green-deployment, but it doesn't look like it is included in the RDS [IRSA permissions](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/blob/main/main.tf#L218-L233).

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by tom-j-smith** [comment]
These are the requested permissions:
```
create-blue-green-deployment
switchover-blue-green-deployment
describe-blue-green-deployments
delete-blue-green-deployment
```

**Comment by tom-j-smith** [comment]
Had a discussion with Poornima about the current state of the [blue-green-deployment update to the RDS module](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/tree/blue-green-deployments). Changes have been made to allow the IRSA module to be able to run the following AWS CLI commands which has also been tested from a service pod:

```
create-blue-green-deployment
switchover-blue-green-deployment
describe-blue-green-deployments
delete-blue-green-deployment
```

We do have some concerns about how open the required permissions are, they are listed below:
- [Ability to create, delete and switchover ANY bdg-* deployment.](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/blob/blue-green-deployments/main.tf#L256-L270)
- [Ability to describe ANY blue-green-deployment](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/blob/blue-green-deployments/main.tf#L285-L296) (this combined with the previous means anyone could switch any blue-green deployment regardless)
- [Ability to tag and create read replicas for ANY RDS instance](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/blob/blue-green-deployments/main.tf#L272-L284) 

There may be ways of being able to lock these permissions down such as the [use of tags](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_iam-tags.html)

**Comment by poornima-krishnasamy** [comment]
The request for this ticket is to allow users to perform blue-green deployment of the rds instances on their own.

Based on the testing did on the permissions required for this feature using this [branch](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/tree/blue-green-deployments), a user could only do blue-green deployments for minor upgrades. In order to perform major upgrades, the policy will need additional permissions to create db-parameter-group for the upgrade version. 

[Ability to tag and create read replicas for ANY RDS instance](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/blob/blue-green-deployments/main.tf#L272-L284) allows any user to tag any other rds resource. The tag based resource filtering is important when accessing resources in aws console. By allowing one policy to tag all resource would open the risk ofone team have ability to restart other team rds instances.

And without these permissions, we couldnt make the blue-breen deployment to work on the command line.

Hence, we are not progressing further with this feature. We can look into what issues you face with the current approach for upgrades and see if we can improve them in anyway
