### ISSUE TITLE
hosted_services dynamo item exceeded the maximum allowed size

### ISSUE THREAD

**Issue by tom-j-smith** [ministryofjustice/cloud-platform#5285]
## Background

The individual namespace cost report pages last successful run was on 2024-01-23 04:37:07, and has been failing since then. This is due to there being enough namespaces that causes the DynamoDB item for hosted_services to exceed 400KB ([item limit](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ServiceQuotas.html#limits-data-types)).

## Approach

AWS suggests [storing large objects in S3 and store the object identifier in your DynamoDB item](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-use-s3-too.html#bp-use-s3-too-large-values).

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jackstockley89** [comment]
We are going to do a rewrite, of how the data is stored, getting manager to send the data to s3 instead of the frontend, then have the frontend just read the data from the s3. this should simplify how data is stored and read. Also will look at replacing the frontend from ruby to go. This will only be done for hosted_services and then in the future we can start to move the other reports across.
