### ISSUE TITLE
Fix Service Account Module

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#5418]
## Background
Having identified the 1.27 warning issue with our implementation of the terraform service account module:

https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#auto-generated-legacy-serviceaccount-token-clean-up

We have a branch which has removed the secret referencing inside of the service account resource:

https://github.com/ministryofjustice/cloud-platform-terraform-serviceaccount/tree/remove-sa-secret-ref

This has been tested on our a`bundant` namespace, no change occurs within the token itself.

We are now just waiting for Peter Phillips to test this branch against some of his workloads to verify this resolves his CircleCI warning issues. He has a merged in PR completed [here](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/3679), but still just needs to test running a pipeline in CircleCI following this switch. He will be in touch with the team week starting 2/4 after BH weekend.

Then we can cut a new release and roll out.

NOTE:
We need to ensure that newly managed secrets once this change goes in, do not get labelled as legacy. This can be checked by rotating a secret with the module, and then having a user trigger a CircleCI run, and verifying that this action does not add:

```
  labels:
    kubernetes.io/legacy-token-last-used: "2024-**-**"
```

to the token containing secret.

<!- - Describe background of the story -->

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
tt

**Comment by poornima-krishnasamy** [comment]
- Tested on several namespaces with the help of Peter Philips
 - The release https://github.com/ministryofjustice/cloud-platform-terraform-serviceaccount/releases/tag/1.1.0 doesnt rotate any existing secrets. It only removes the reference from the sa. 
 - After the new release, users dont see the warning: 
```
Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
```

NOTE:
We need to ensure that newly managed secrets once this change goes in, do not get labelled as legacy. This can be checked by rotating a secret with the module, and then having a user trigger a CircleCI run, and verifying that this action does not add:

  labels:
    kubernetes.io/legacy-token-last-used: "2024-**-**"
to the token containing secret.
On this part: The secrets are still marked with label: `kubernetes.io/legacy-token-last-used`. Thats because of the enhancement to reduce the secret based serviceaccount tokens. All secrets that has serviceaccount referenced are marked with label `kubernetes.io/legacy-token-last-used` as of 1.27. https://github.com/kubernetes/kubernetes/blob/v1.27.12/pkg/serviceaccount/legacy.go

In 1.28 and 1.29, more audit annotations are added to determine auto-generated and manually created secrets. 
https://github.com/kubernetes/kubernetes/pull/118598
