### ISSUE TITLE
Investigation: Default Service Accounts

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#5419]
## Background
Namespaces which were created before k8s 1.24 likely still have legacy default service accounts with legacy token secrets. For example `abundant-namespace-dev`:

```
Active namespace is "abundant-namespace-dev".
❯ k get sa
NAME                                 SECRETS   AGE

default                               1                 2y273d
```
We need to find out:

- Are these default service account tokens triggering warnings in users deployments?
- If we delete the default service account, what is the impact (if any) on pods that use the default service account (these are any pods that do not specify their own SA)
- If we delete an old namespace default service account, will it immediately refresh with a non legacy token setup?

Test the above scenarios in abundant.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
- Are these default service account tokens triggering warnings in users deployments?

Answer: No, they dont show any warning during application deployment

- If we delete the default service account, what is the impact (if any) on pods that use the default service account (these are any pods that do not specify their own SA)
The SA in namespaces that are created after 1.24 which doesnt have secret-token referenced, when deleted, the api recreated back. No impact on the pods running, No restart required

- If we delete an old namespace default service account, will it immediately refresh with a non legacy token setup?
The SA created before 1.24 has a secret referenced. When the SA got deleted, the secret referencing it was also deleted but it didnot recreate the secret. This is expected because as of 1.24, sa doesnt auto-generate secrets. The pod still have the default SA referenced. But there is no downtime or token being called inside the pod. 
https://kubernetes.io/docs/concepts/security/service-accounts/#default-service-accounts

**Comment by poornima-krishnasamy** [comment]
In order to get rid of old default serviceaccounts, we should rotate all default serviceaccounts and create a fresh one

**Comment by jackstockley89** [comment]
update the script to create a list with dynamic output for the delete command

`kubectl get sa --all-namespaces -o json | jq -r '.items[] | select(.secrets != null) | select(.secrets[].name | contains("default-token")) | "kubectl delete sa " + .metadata.name + " -n " + .metadata.namespace' > delete-sa.sh`

**Comment by jackstockley89** [comment]
zero legacy sa remain.

[legacy default sa search and delete command creation](https://gist.github.com/jackstockley89/56078dda6e7bddd323771db3466ad6e6)
