### ISSUE TITLE
Permanent credentials for C100

### ISSUE THREAD

**Issue by kalvinSolirius** [ministryofjustice/cloud-platform#5465]
[ON HOLD] - Awaiting conversation with user upon their return from annual leave week commencing 29/04.

## Service name

C100

## Service environment

- [x ] Dev / Development
- [x ] Staging

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Currently, C100's upload client requires credentials from a web_identity_token that is refreshed daily or multiple times a day. This is frustrating as all members of the team needs to grab the new token from the pods for tests to run and to get onto the pages with uploads/ submitting the application.

## Problem description

The C100 staging/ dev uses the token instead of permanent credentials. This makes it difficult for devs/QA to test and use the service.

## Contact person

Kalvin Lyu - kalvin.lyu@hmcts.net

**Comment by sj-williams** [comment]
Emailed user for further info

**Comment by sj-williams** [comment]
[ON HOLD] - Awaiting conversation with user upon their return from annual leave week commencing 29/04.

**Comment by sj-williams** [comment]
Discussed this issue with @kalvinSolirius. Most likely the solution to this issue involves some re-architecting upload client and testing strategy - since currently we dont have a means of external parties (ie CircleCI) seamlessly refreshing auth aka IRSA in kubernetes workloads.

User is going to take a look at alternative approach possibly with IRSA/Service pod in favour of constantly having to update stale tokens from IRSA based pod.

Closing ticket, any further questions on the topic we can assist with via #ask channel or additional support ticket.
