### ISSUE TITLE
Spike pprof tool to understand prometheus sharding

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#5643]
## Background

As part of Improving Prometheus and monitoring system, we need debugging tools to analyse the which metric scrapping takes high cpu and memory. 

According to the below article, pprof seems to be generate a graph with shards and can zoom into level of each metric that is scrapped and the resource consumption.

https://medium.com/criteo-engineering/how-we-reduced-our-prometheus-infrastructure-footprint-by-a-third-8bf8171e46b1

## Approach

Install the tool and identify if this give more information about metrics and resource usage per metric scraped.
If this tool is found helpful, write a runbook or add to existing runbook about the installation procedure and how to use

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jaskaransarkaria** [comment]
`pprof` is a Go profiling tool that makes it easy to look at CPU and memory usage, you can run this against promethues endpoint for useful debugging insights.

Prometheus' heap memory profiling endpoint is available at /debug/pprof/heap. While you can view this endpoint in the browser, the contents are easier to interpret by using the Go command-line tool to fetch and visualise the memory usage.

Keep an eye on cpu/ mem when running pprof. the tool is simple to use, follow these instructions:

- port forward prometheus so that you can access the debug endpoint
- `go tool pprof http://localhost:54455/debug/pprof/heap` this will put you into a pprof shell
- `top` will get you the heap breakdown

useful links:

https://training.promlabs.com/training/monitoring-and-debugging-prometheus/profiling/profiling-heap-memory-usage/
https://www.robustperception.io/analysing-prometheus-memory-usage/
