### ISSUE TITLE
Enable AWS shield Advanced for Cloud Platform

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#5644]
## Background

There has been spikes to explore AWS Shield Advanced and Modernisation Platform have enable for specific features

https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/enabling-shield-advanced.html#enabling-aws-shield-advanced-for-production-applications

## Approach

As part of this ticket:
-  Investigate what benefits by enabling AWS Shield Advanced
- Investigate any problems we will face by enabling AWS Shield Advanced
- What are the important rules and actions that we could implement and create tickets to implement the rules
- Enable them programatically
- Add runbook/readme on how to this is configured

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by timckt** [comment]
[Modernisation Platform ticket](https://github.com/ministryofjustice/modernisation-platform/issues/1601)

[Modernisation Platform ADR](https://github.com/ministryofjustice/modernisation-platform/blob/main/architecture-decision-record/0018-use-aws-shield-advanced.md)

**Comment by timckt** [comment]
Shield advanced is enabled using AWS Firewall Manager policies. This is managed in the [aws-root-account](https://github.com/ministryofjustice/aws-root-account/blob/main/organisation-security/terraform/firewall-manager.tf) Terraform code. 
Since this is an organizational-level feature, our account does not incur additional costs.
Both our Cloud Platform and Cloud Platform Ephemeral Test AWS Accounts have already enabled AWS Shield, but there are currently no resources to be protected in the Cloud Platform AWS account. 

![Image](https://github.com/user-attachments/assets/ec5d43ea-f0a7-44e8-9560-0adb01d1d3b6)

We can use Shield Advanced for advanced monitoring and protection with the following resource types:

- Amazon CloudFront distributions. For CloudFront continuous deployment, Shield Advanced protects any staging distribution that's associated with a protected primary distribution.

- Amazon Route 53 hosted zones.
- AWS Global Accelerator standard accelerators.
- Amazon EC2 Elastic IP addresses. Shield Advanced protects the resources that are associated with protected Elastic IP addresses.
- Amazon EC2 instances, through association to Amazon EC2 Elastic IP addresses.
- The following Elastic Load Balancing (ELB) load balancers:
  - Application Load Balancers.
  - Classic Load Balancers.
  - Network Load Balancers, through associations to Amazon EC2 Elastic IP addresses.

Our ingress load balancer is a Network Load Balancer (NLB). According to [AWS documentation](https://docs.aws.amazon.com/waf/latest/developerguide/ddos-protections-by-resource-type.html#:~:text=Network%20Load%20Balancers%2C%20through%20associations%20to%20Amazon%20EC2%20Elastic%20IP%20addresses.), we cannot directly add Network Load Balancers to the AWS Shield resource for advanced DDoS protection. Instead, Network Load Balancers must be protected through their association with Elastic IP addresses.

Currently our cluster's network load balancer is created by [ingress-controller](https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller), and the public IP is auto assigned by AWS and we cannot add this public IP to AWS Shield.

- Created ticket https://github.com/ministryofjustice/cloud-platform/issues/6000 for this


Currently we have enabled `Cloud Platform Ephemeral Test` account with [an auto remediation policy](https://github.com/ministryofjustice/aws-root-account/blob/main/organisation-security/terraform/locals.tf#L132).

Once Cloud Platform Ephemeral Test is added to the `local.shield_advanced_auto_remediate.accounts`, it will inherit the WAF rule and the protect resource(EIP, ALB and CLB) in AWS Shield. If we do not inherit the resource from Firewall Manager Policy, it will be easier for us to add the resource to Shield. (We else need to use some data block with external provider to execute aws cli command to retrive those resource)

**Comment by timckt** [comment]
# Methods for Adding Resources to AWS Shield

If we would like to add resources to AWS Shield, there are two methods:

## Method 1: Add our CP AWS account to the [moj-aws-root-account-list](https://github.com/ministryofjustice/aws-root-account/blob/main/organisation-security/terraform/locals.tf#L132) 

When our account is added to the [local.shield_advanced_auto_remediate.accounts](https://github.com/ministryofjustice/aws-root-account/blob/main/organisation-security/terraform/locals.tf#L132)), MOJ AWS [Firewall Manager](https://github.com/ministryofjustice/aws-root-account/blob/main/organisation-security/terraform/firewall-manager.tf#L5) will create an empty WAF policy and automatically add EIP, CLB and ALB resources to AWS Shield.

For each in-scope resource that's not already associated with a AWS WAF web ACL, Firewall Manager associates an empty AWS WAF web ACL. The empty web ACL is used for Shield monitoring purposes. If we then associate any other web ACL to the resource, Firewall Manager removes the empty web ACL association.

More about AWS Shield Advanced policies from Firewall Manager [here](https://docs.aws.amazon.com/waf/latest/developerguide/shield-policies.html)

Example Working Branch [here](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/shield_inherit/terraform/aws-accounts/cloud-platform-ephemeral-test/account/shield_inherit.tf)

## Method 2: Use a data block with an external provider to retrieve the resource individually.  

If we do not want to add our account to the [local.shield_advanced_auto_remediate.accounts](https://github.com/ministryofjustice/aws-root-account/blob/main/organisation-security/terraform/locals.tf#L132)), we can add resources to AWS Shield by using data block with external provider to do some bash aws cli command to get resource value and add to Shield.

A example if we want to add EIP to Shield
```
data "external" "aws_eip_allocation_ids" {
  program = [
    "bash", "-c",
    "aws ec2 describe-addresses --query 'Addresses[*].AllocationId' --output json | jq -c 'to_entries | map({(\"eip_\" + (.key | tostring)): .value}) | add'"
  ]
}

 resource "aws_shield_protection" "eip_protection" {
   for_each     = data.external.aws_eip_allocation_ids.result
   name         = each.key
   resource_arn = "arn:aws:ec2:${var.aws_region}:${data.aws_caller_identity.current.account_id}:eip-allocation/${each.value}"
 }
```

Example Working Branch [here](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/shield_self_manage/terraform/aws-accounts/cloud-platform-ephemeral-test/account/shield_self_manage.tf)

## Comparison

Method | Advantages | Disadvantages
-- | -- | --
Method 1: Auto Inherit | - Automatically adds all resources (EIP, ALB, CLB) to Shield once created.<br/>- Streamlined process. | - Limited flexibility.<br/>- Requires manual import of aws_wafv2_web_acl from AWS Firewall Manager.
Method 2: Manual Add | - Greater flexibility.<br/>- Can selectively add resources to Shield. | - Resources are not automatically added to Shield.<br/>- Requires re-running Terraform code for new resources.


Currently we have enabled `Cloud Platform Ephemeral Test` account with [an auto remediation policy](https://github.com/ministryofjustice/aws-root-account/blob/main/organisation-security/terraform/locals.tf#L132).

Once Cloud Platform Ephemeral Test is added to the `local.shield_advanced_auto_remediate.accounts`, it will inherit the WAF rule and the protect resource(EIP, ALB and CLB) in AWS Shield. If we do not inherit the resource from Firewall Manager Policy, it will be easier for us to add the resource to Shield. (We else need to use some data block with external provider to execute aws cli command to retrive those resource)

**Comment by timckt** [comment]
In AWS Shield Advanced, when setting up automatic mitigation and remediation for Distributed Denial of Service (DDoS) attacks, the available actions that can be taken as part of the remediation strategy and include the following:

- Allow: No action is taken automatically when a potential DDoS attack is detected. 

- Count: This action counts the number of requests that match the criteria defined in a WAF rule but does not block them. This can be useful for monitoring and analyzing traffic patterns without impacting legitimate traffic.

- Block: Blocks requests that match the criteria defined in a WAF rule. This action prevents the malicious traffic from reaching your application. 

- Rate-Based Rules: With rate-based rules, AWS WAF can automatically block or throttle IP addresses that exceed a specified request rate. This can help mitigate volumetric attacks by slowing down or blocking IPs that generate excessive traffic.

In our situation, we should go with Count action with Rate based rules for monitoring purpose.
