### ISSUE TITLE
 Nameservers in the Cloud Platform AWS account

### ISSUE THREAD

**Issue by vijaykannan21** [ministryofjustice/cloud-platform#5727]
As a Operations Engineering Team
We want to be able to obtain Cloud Platform Nameserver information
so that we can better handle delegation requests with less work for users or the CP team, and so that we better track the active status of existing delegations.

## Service environment

- [ ] Other

## Problem description

We need the nameserver  Details for the Cloud Platform Environment 

## Contact person

1. Antony Bishop
2. Connor Glynn
3. Vijayaprabhakaran

**Comment by poornima-krishnasamy** [comment]
Hi @vijaykannan21 , from what I understand from the ticket, this should be a automated script providing the details to Operations Engineering. This is not something we currently have and needs to be implemented. Hence, It would be good to understand how you want the data in order for you to track the delegation requests and existing delegations. 

One possible approach is: we provide a list of hosted zones created in CP and each Nameservers records under each of the hosted zone in a JSON format uploaded in a s3 bucket. Operations engineering can create a namespace which can have read access to that s3 bucket (We can decide on the frequency of freshness).
Would that be ok? Do you have any other suggested approached so it is easy for you to reconcile from your end?

What is the urgency for this ticket?

**Comment by connormaglynn** [comment]
Hi @poornima-krishnasamy 👋 

Thank you for the quick response on this! 🚀

For a bit more context of what we're working on, Operations Engineering are currently the MoJs Domain Registrar i.e. we handle all Top Level Domains registrations and Sub-Domain Delegations 🤹

## The Problem 😱

One use case of the Sub-Domain Delegation is delegating the ownership of a domain to the Cloud Platform, which (at a very high level) happens in the following steps:

- Cloud Platform user creates Hosted Zone in Cloud Platform (this creates some Name Servers for the user ✨)
- Cloud Platform user asks Operations Engineering to delegate a domain to newly created Name Servers
- Operations Engineering creates a NS record to delegate the domain to provided Name Servers

And here's a High-level AS IS diagram of that process if it makes it any easier 👇 🧑‍🎨

![image](https://github.com/ministryofjustice/cloud-platform/assets/66882795/fc928b41-588f-4aca-bd8c-2e959b74b4f5)

👆 The problem here, is that Operations Engineering have no way to determine that the Name Servers the users provide are actually hosted in Cloud Platform 😬 So if the user provides incorrect Name Servers, we open up the domain to be hijacked 💥 (or more likely the user ends up very confused)

Another problem is that if the user deletes the Hosted Zone in the future, and Operations Engineering doesn't delete the record that delegates, we again open up the domain to hijacking 💥

## The (potential) Solution 🥳

Ideally, Operations Engineering want to implement a process to determine that the Name Servers that a user provides us are (and continue to be) owned by the Cloud Platform 🥳 This way when a user sends us a request to delegate a domain to Cloud Platform, we can verify that the information is correct ✅ Also, in the longer term, we can check that the user hasn't subsequently deleted their Hosted Zone in Cloud Platform 🔥

I believe the simplest method would be providing some form of programmatic ReadOnly access to Route53 in the Cloud Platform AWS Account 👀 But we can scope the access as Cloud Platform sees fit 😁

And here's another High-level TO BE diagram of the process if it makes it easier 👨‍🎨

![image](https://github.com/ministryofjustice/cloud-platform/assets/66882795/4c3672de-ba9b-45fc-ba90-798a9c293152)

If programmatic ReadOnly access to Cloud Platforms Route53 is not possible, then yes we would need Cloud Platform to spin up and maintain some infrastructure to read and export this information to somewhere readable 📖 But I'm hoping to minimise the burden on yourselves to achieve getting this information! 😁

The idea at the moment is just Proof of Concept, but feel free to ping me (or Operations Engineering) if you'd like to chat about it more 😁

**Comment by vijaykannan21** [comment]
I just had a conversation with Chike Chinukwue (Delivery-Manager), cloud platform team. 

- The ticket has not yet started working. For the current sprint, he stated that he will discuss this with the team during tomorrow's huddle.

**Comment by sj-williams** [comment]
IAM resources added at account level ^

Awaiting feedback on effectiveness of permissions scope

**Comment by connormaglynn** [comment]
Hi all 👋 

Managed to use the credentials to successfully list the HostedZones in Cloud Platform 🥳

I'm happy for this item to be marked as done ✅ We need to continue the work on our side to make use of this access now 👷

Thank you all for the support and speedy turnaround on this! 🚤  especially @sj-williams 🤩
