### ISSUE TITLE
Cortex XSIAM IAM integration

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/cloud-platform#5933]
## Background

MIP would like us to integrate XSIAM with IAM using the IAM plug in.
https://xsoar.pan.dev/docs/reference/integrations/aws---iam-identity-center

## Approach

Evaluate what information the IAM plugin gives and what permissions it needs, discuss with team if we want to do this integration.

## Questions / Assumptions

Contact Ashwin John for more information

## Definition of done

- [ ] research done
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ashwinmoj** [comment]
For more information on the requirements for these integrations, please refer to the following links:
• [AWS IAM Integration](https://xsoar.pan.dev/docs/reference/integrations/aws---iam)
• [AWS IAM Identity Center Integration](https://xsoar.pan.dev/docs/reference/integrations/aws---iam-identity-center)
• [AWS Integrations Authentication](https://xsoar.pan.dev/docs/reference/articles/aws-integrations---authentication)

**Comment by ashwinmoj** [comment]
Hi, could I please ask if there have been any updates on reviewing this task?

**Comment by ashwinmoj** [comment]
To provide additional context for this request: the purpose of this integration is to enhance alerts from the AWS environment on the XSIAM platform. Specifically, we aim to use this integration for alert enrichment by querying information about Amazon resources, which will assist the SOC in investigating AWS-related alerts.

I've attached the list of commands available on XSIAM after the IAM integration is complete. We are specifically interested in the commands that query information, rather than making any changes to the platform. This includes commands starting with aws-iam-get and aws-iam-list. So when configuring the integration, we need to set up a role that allows these commands to be executed.

[AWS IAM vs AWS Identity Center commands.xlsx](https://github.com/user-attachments/files/16763528/AWS.IAM.vs.AWS.Identity.Center.commands.xlsx)

Mod Platform data is already being ingested on XSAIM via Amazon S3 and Cloudwatch. The SOC team will be the primary users of this data, investigating any alerts from the AWS environment and escalating any concerning incidents according to the agreed process.

**Comment by ashwinmoj** [comment]
For the integration we’ll need to use the Access Key and Secret Key authentication option.

As part of the configuration for the Access Key and Secret Key authentication you create a role and can specify granular IAM permissions. This looks to be the list of actions you can choose from: [Actions - AWS Identity and Access Management](https://docs.aws.amazon.com/IAM/latest/APIReference/API_Operations.html) . This will allow you to only give the account the privileges it needs for the particular commands you would like to use.

Full steps for setting up the account and integration for the Access Key and Secret Key authentication option are here: [AWS Integrations - Authentication | Cortex XSOAR](https://xsoar.pan.dev/docs/reference/articles/aws-integrations---authentication#configuration-using-access-key-and-secret-key)

**Comment by richgreen-moj** [comment]
See outcome of https://github.com/ministryofjustice/modernisation-platform/issues/7605 for reference. This story is no longer required

**Comment by ashwinmoj** [comment]
I will be on annual leave for two weeks starting from next week and will return on September 30th. During my absence, @YasJustice/ yaasseen.aumeer@justice.gov.uk from the MIP team will be available for any assistance or inquiries related to these tickets.

**Comment by davidkelliott** [comment]
No longer required as users are managed in Github/Auth0 this does not give the value we want.
