### ISSUE TITLE
Use `-out` to pass terraform plan to apply step

### ISSUE THREAD

**Issue by mikebell** [ministryofjustice/cloud-platform#6008]
## Background

Currently when we run terraform plan and apply we're not passing the state through to the apply step. This means we're technically running plan twice, if we use `-out` we can pass the plan between the steps and cut execution time down. We can also gaurantee that what we see in the plan step is what will happen in the apply step.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jaskaransarkaria** [comment]
Because of the way plan files work, it makes rerunning failed terraform difficult, as layers are marked as stale after they are run.

This means that:

- we need a pipeline to rerun those layers not from a plan file (or a mechanism to turn off plan files) OR we could push a new plan and overwrite the old stale plans?
- It also means that this workflow would introduce too much friction for user workloads in environments

**Comment by jaskaransarkaria** [comment]
If you need to rerun an apply that uses a stale plan:

1. run a new plan in concourse 
2. retry the apply in concourse
