### ISSUE TITLE
pvb public and pvb2 staging ELB not in service

### ISSUE THREAD

**Issue by StupidCodeFactory** [ministryofjustice/cloud-platform#61]
## Service name

pvb public pvb2

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

cant' deploy to either prod or staging on either apps

## Problem description

ELB's seems to not be in service

## Contact person

@stupidcodefactory

**Comment by razvan-moj** [comment]
Several VMs were 'out of service' in the load balancer because the Salt run errored at a module added on May 14 (collectd.docker) that does exist and work, but was declared 'not found'. A fab update run in the VM (using the 'ubuntu' user key from Rattic) fixed the issue. 
https://ci.service.dsd.io/view/PVB2/job/pvb-deploy-public-staging/ & https://ci.service.dsd.io/view/PVB2/job/pvb-deploy-staff-staging/ are green now
