### ISSUE TITLE
Low Priority Alarms: VeleroBackupPartialFailures in manager

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#6426]
## Background
This alert is firing regularly in our `manager` cluster.

ie:
https://mojdt.slack.com/archives/C8QR5FQRX/p1731067433688079

Investigate, find cause, fix.

**Comment by jackstockley89** [comment]
Error in alarms: [slack](https://moj.enterprise.slack.com/archives/C8QR5FQRX/p1731953063660989)
 I checked AlertManager and there is nothing in the console about this alert 

OpenSearch log for that time in Manager there is only one entry: [open search](https://app-logs.cloud-platform.service.justice.gov.uk/_dashboards/app/data-explorer/discover#?_a=(discover:(columns:!(_source),isDirty:!t,sort:!()),metadata:(indexPattern:d2265940-0d2e-11ef-bf63-53113938c53a,view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-11-18T18:04:26.000Z',to:'2024-11-18T18:04:27.000Z'))&_q=(filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:bb90f230-0d2e-11ef-bf63-53113938c53a,key:kubernetes.namespace_name,negate:!f,params:(query:velero),type:phrase),query:(match_phrase:(kubernetes.namespace_name:velero)))),query:(language:kuery,query:'')))

The only error complains about client-side throttling and nothing mentions partial backup failing, I have followed this error to an issue on Velero and it points to the following issue [velero GitHub issue](https://github.com/vmware-tanzu/velero/issues/3191)

**Comment by jackstockley89** [comment]
Since upgrade are seeing different behaviour [open search](https://app-logs.cloud-platform.service.justice.gov.uk/_dashboards/app/data-explorer/discover#?_a=(discover:(columns:!(_source),isDirty:!t,sort:!()),metadata:(indexPattern:d2265940-0d2e-11ef-bf63-53113938c53a,view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-12-12T09:30:00.000Z',to:now))&_q=(filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:bb90f230-0d2e-11ef-bf63-53113938c53a,key:kubernetes.namespace_name,negate:!f,params:(query:velero),type:phrase),query:(match_phrase:(kubernetes.namespace_name:velero)))),query:(language:kuery,query:'%22due%20to%20client-side%20throttling,%20not%20priority%20and%20fairness%22'))), no longer seeing the error due to throttling

**Comment by jackstockley89** [comment]
Should Talk about this in standup on Monday
