### ISSUE TITLE
Proposal for improvements to AWS-RDS Grafana dashboard

### ISSUE THREAD

**Issue by KristianGregor** [ministryofjustice/cloud-platform#6463]
## Service name

Activities & Appointments
Visit Someone In Prison

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Details of proposal
This concerns the AWS-RDS grafana dashboard, in particular the graph that FreeAbleMemory/FreeStorageSpace
![Image](https://github.com/user-attachments/assets/fb543603-8d27-46bd-8dd2-591e8e0adb74)

I'm struggling to understand the reason for putting FreeableMemory into the same graph as FreeStorageSpace. FreeableMemory concerns RAM, whereasFreeStorageSpace is about disk storage. Although these are both a form of memory, and measured in GB, they otherwise don't seem to have any meaningful relationship, so its not clear why you would want them in the same graph. In addition, FreeStorageSpace on a large database would be on a totally different scale to FreeableMemory, leaving the latter as a flat line at the bottom of the graph.

In addition to this, its hard to see at present what's really going on with storage space on the RDS instance. It would be useful to see how much space is actually allocated (db_allocated_storage), so you could see free space, allocated space, and thus determine used space. I'd propose that this graph would better with FreeableMemory removed (possibly put into its own or merged with another graph), and replaced with AllocatedStorage. 

## Contact person
Kristian Gregory, TA in HMPPS Digital

**Comment by sj-williams** [comment]
Following upgrade of our out-of-the-box [RDS grafana dashboard](https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards) , have been looking into setting up a better view of additional storage metrics per instance.

However, it turns out that at this time `FreeStorageSpace` is the only CW metric available for this; `AllocatedStorage` is an _account-wide_ metric:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-metrics.html

Based on this, I've spoken with Kristian and we're going to close this one off, and instead look at some other ways of getting more useful metrics at instance level.
