### ISSUE TITLE
Parse the JSON fields from fluentd so they can be searchable in Kibana.

### ISSUE THREAD

**Issue by vijay-veeranki-moj** [ministryofjustice/cloud-platform#678]
## Background

User raised a support request to see the possibility for logstash/fluentd to parse the JSON fields(https://www.elastic.co/guide/en/logstash/current/plugins-filters-json.html) and make them queryable in Kibana

## Proposed user journey

If the JSON filed can be parsed as expected, use can search the fields in Kibana, using the below approach

## Approach

shipping the logs using awslogs client to ship them into AWS logs, then from AWS logs they’ll be automatically delivered to the lambda function of our choice which will do the parsing and conversions.

## Which part of the user docs does this impact

https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/master/helm-charts/fluentd-es/README.md

## Questions / Assumptions

Worked on this task to parse the JSON fields but couldn't get the expected results after parsing.

As shown in the demo, fields are parsed but missing the field mapping which
is missing the actual requirement of searching the parsed fields.

Refresh field list in Kibana management didn't help in mapping the fields.

some of the issues identified:

Conflict of fields
Data parsing too much of data
Buffer warning
[warn]: [elasticsearch] failed to write data into buffer by buffer overflow action=:block
'filters' parameter is deprecated: filters has been renamed as matches.

So this approach did not work as expected, so need to try other alternative ways

actual support req:
https://github.com/ministryofjustice/cloud-platform/issues/619

## Definition of done

JSON filed can be parsed, use can search the fields in Kibana

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by rossjones** [comment]
There was a new release of the JSON filter last month which claims to have some 'unnamed' fixes, https://github.com/logstash-plugins/logstash-filter-json/blob/v3.0.6/CHANGELOG.md - might it be possibly fixed in there?

**Comment by AntonyBishop** [comment]
We'll need to do some further user research on this to better understand user needs so that we can identify some potential routes to research.

**Comment by AntonyBishop** [comment]
User feedback:
My experience with this before has been with Logstash rather than Fluentd, and I know this is definitely possible with Logstash (GOV.UK’s logging does this, and it’s possible that the previous cloud platform/template deploy logging setup did too, before it was moved to AWS)
I’m happy to have a chat about how useful this is - basically this kind of query in Kibana has been my go-to way of understanding how services are behaving in production for quite a while, and not having access to it is pretty limiting, especially given the expectations on teams to support their applications more fully.

**Comment by MatMoore** [comment]
Here's another data point based on my experience with kibana at GDS. My team is not on the cloud platform yet, but I'm interested in what the cloud platform can offer in this area because the apps my team owns are already dockerised, but we run on ECS and depend on cloudwatch for monitoring and logging.

I worked on GOV.UK as well, and although it was often a struggle to get the kibana syntax right, as long as somebody could figure it out once, we were able to build up a [knowledge base of useful queries](https://docs.publishing.service.gov.uk/manual/kibana.html). 

If the application gets a lot of traffic, it's very difficult to filter out the noise with just keyword searches and times. Off the top of my head some common queries we used filters for were:

- Searching by path if we have reports that a particular page doesn't work
- Searching by 500 status if we detect the application is not healthy
- Counting the number of 500 responses served during an incident so we have an idea of how many people are affected
- Travel alert notifications used tracking ids so we could filter by ID to receive all logs related to the processing of a particular update to see where it had failed

I believe the default install of kibana comes with some examples in the saved searches as well.

I think the exact use cases will be different for different teams, but if some standard fields are available out of the box for any cloud platform service, then that enables developers to answer questions about their service on demand. I think it's hard to predict what fields will be useful in advance because you don't know what you will need to know in future.

On the teams I was on at GDS we had some problems with inconsistent naming of fields, but there was some work to [standardise fields across different applications](https://gds-way.cloudapps.digital/manuals/logging.html#http-fields). That enabled people to jump between projects and still be able to support the apps to some degree.

**Comment by rossjones** [comment]
Is a potential fix for this to update https://ministryofjustice.github.io/cloud-platform-user-docs/99-other-topics/004-kibana/#introduction and explain that you must log in a format that fluentd can parse, so for Ruby that would be something like https://github.com/fluent/fluent-logger-ruby (which be default seems to want to use either IP or domain sockets but may well work with stdout)?  I understand that K8s logs to fluentd by default, but that isn't really clear anywhere.

I'm only suggesting this as it will likely block our move of PVB to Cloud Platform and is a risk for the allocation tool we're hoping with go into beta later this month....

Happy to try this potential solution out on the allocation tool...

**Comment by alkar** [comment]
> On the teams I was on at GDS we had some problems with inconsistent naming of fields, but there was some work to standardise fields across different applications. That enabled people to jump between projects and still be able to support the apps to some degree.

This ^ I believe we'll need to define some schema before we can actually parse structured logs. The problem is (and again, I'd be very happy if someone were to prove me wrong) that ES has an internal schema (template) by which it will index fields (and it will guess the field types if no template is defined). That means that the fields we extract need to be uniform, otherwise we risk losing logs entries that don't fit - ES will typically respond with a `400`, rejecting the entry, and that has the side effect of filling up `fluentd` buffers which then causes all sorts of problems.

**Comment by rossjones** [comment]
I don't recall there ever being a mapping with logstash, instead we wrote filters, or grok-filters that would promote fields from the incoming JSON blob (or log line) into fields (https://www.elastic.co/guide/en/logstash/current/field-extraction.html) without a mapping.

**Comment by AntonyBishop** [comment]
We have created a story #725 to spike a possible solution to this problem.

@rossjones would you be willing to work with my team on this spike?

**Comment by rossjones** [comment]
@AntonyBishop Of course!

**Comment by AntonyBishop** [comment]
Issue closed. Issue resolved by #266

**Comment by alkar** [comment]
> Issue closed. Issue resolved by #266 - [ministryofjustice/cloud-platform-infrastructure#266](https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/266)
> 
> Comms issued in #cloud-platform-update channel on 22nd May 2019.

To be clear, this issue resolved structured nginx access log (which makes our design almost equivalent to what template-deploy offered). We're having discussion on how to best accommodate structured application logs but it's a more complicated issue since applications can define their own structure in logs.

We'll be updating soon, once we have the design finalised.
