### ISSUE TITLE
Assess impact of Unprivileged Pod Security Policy on CLA (Public)

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#714]
## Background

Having documented the differences in Pod Security Policies we will ask the to determine the impact of changes on their product.

## Proposed user journey

N/A

## Approach

As the team to assess the impact.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

We want to understand what breaks/stops working?
Ho much reworking would be required to work with the new PSP

## Definition of done

- [ ] CLA team complete impact assessment
- [ ] CLA Team and CP Team discuss assessment to understand impact
- [ ] Decision can be made on how to implement changes

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by mtrblmoj** [comment]
Moving this ticket to BLOCKED, There seems to be a limitation to  Kubernetes.

PSP will be applied to pods as expected. However, it is possible to bypass the policies with Deployments. 

What we know: 

- Deployments are created by the Controller Manager (CM)

- We should apply the least privileged policy to the (restricted) to the CM, instead of kube-system

- The CM is created by KOPS, which makes it harder to tweak the CM config.

**Comment by AntonyBishop** [comment]
Story has changed direction. No longer applies.
