### ISSUE TITLE
Document differences between Pod Security Policies

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#715]
## Background

We are thinking of implementing a 3rd PSP - Unprivileged.

We already have Privileged and Restricted in Live 1.

So we can make clear the differences in policies and understand how these would impact teams we want to write up our existing yaml into a document of some sort.

This will be used with teams so that they can understand impact on their products and how they work.

## Proposed user journey

N/A

## Approach

Convert yaml into some form of document to inform impact assessment with teams.

## Which part of the user docs does this impact

N/A

## Definition of done

- [ ] Document created and reviewed with Tony

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by mtrblmoj** [comment]
The expected behaviour of the psp we implemented COULD NOT be fully confirmed.

**Comment by mtrblmoj** [comment]
Moving this ticket to BLOCKED, There seems to be a limitation to  Kubernetes.
PSP will be applied to pods as expected. However, it is possible to bypass the policies with Deployments. 

What we know: 

- Deployments are created by the Controller Manager (CM)

- We should apply the least privileged policy to the (restricted) to the CM, instead of kube-system

- The CM is created by KOPS, which makes it harder to tweak the CM config.

**Comment by mtrblmoj** [comment]
Unblocked, as upstream issue is now resolved
