### ISSUE TITLE
Spike: Test cert-manager DNS management with wildcard certificates

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#757]
Formbuilder will be using wildcard certificates to enable them to create
many 'apps', each with its own domain.

This should just work, 'out of the box' using the same cert-manager DNS
management as for more typical applications, but we should do a quick
spike to verify this.

Definition of done:

On a test cluster;

* Set up a wildcard DNS entry
* Define a hostname within the wildcard on an ingress controller
* Confirm that TLS works correctly with no additional manual steps

**Comment by alkar** [comment]
Closing. This was tested and implemented for formbuilder but instead of a single wildcard DNS entry we've allowed `external-dns` to setup individual records. The reason was that we would otherwise have to define the wildcard record as an annotation to our `nginx-ingress` `Service`, tying it up with our cluster creation process. `external-dns` is able to generate and automatically manage records from `Ingress` hosts so there is no additional cost.

We do use a wildcard certificate, however, to minimise the number of hits on the ACME API.
