### ISSUE TITLE
Enable users to control S3 bucket permissions

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#777]
Our terraform module for creating S3 buckets hard-codes the bucket
permissions:

https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket/blob/master/main.tf

```
data "aws_iam_policy_document" "policy" {
  statement {
    actions = [
      "s3:GetBucketLocation",
      "s3:ListBucket",
      "s3:ListBucketMultipartUploads",
      "s3:ListBucketVersions",
    ]

    resources = [
      "arn:aws:s3:::${aws_s3_bucket.bucket.id}",
    ]
  }
```

We have had a request from Phil Lee in the formbuilder team. They
need to create S3 buckets where the corresponding IAM user does not
have the 'ListBucket' permission.

### Definition of done

 - [x] The S3 bucket permissions come from a variable
 - [x] The variable defaults to our current list of permissions
 - [x] We have an example showing how to override the permissions

**Comment by alkar** [comment]
One issue I see with this is that we probably want to maintain control over the `resources` field in order to limit this to a single bucket.

However, variables in terraform can only be of basic types (no lists!) so then we would have to pass those in using a comma separated list. Do you think that's acceptable?

Additionally, is it fair to assume that having multiple statements is out of scope (ie. you either get the default policy or you can customise its actions specifically)?

**Comment by digitalronin** [comment]
Can we just specify "actions" as a CSV, with the current list as the default?

So, people could override the actions list, and only the actions list.

**Comment by alkar** [comment]
I've ended up taking a different course of action, similar to what I did for `bucket_policy` (#780) which allows us to provide a policy and treat it like a template when it comes to things like the bucket ARN. 

After a chat with @jasonBirchall, I realised we ultimately have control over the policy by virtue of `cloud-platform-environments` reviews, so we don't have to be strict at the module level.

The new release is https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket/releases/tag/3.1 and there's an example of a custom policy.
