### ISSUE TITLE
Update external-dns and cert-manager for live-1

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#802]
## Background

Related to #798

As part of our work to provide custom domains for applications and properly manage them, we've agreed to create zones for services in our cloud-platform account. We want the `live-1` cluster to be able to manage all of the zones in its account.

## Approach

Update the `external-dns` and `cert-manager` configuration so that:
- [ ] these components in `live-1` can access all the Route53 zones in the cloud-platform account
- [ ] the same components in other clusters are only able to access their own dedicated zone, ie. `<cluster-name>.cloud-platform.service.justice.gov.uk`

**Comment by vijay-veeranki-moj** [comment]
Updated external-dns and cert-manager configuration so that:

-components in live-1 can access all the Route53 zones in the cloud-platform account
-components in other clusters are only able to access their own dedicated zone

Raised a PR: https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/246
