### ISSUE TITLE
Do a practice deploy of sentry, using template deploy

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#87]
This is to test that template deploy can build a sentry service. We want to know whether sentry is under template deploy control and if not, how close it gets when you build it with template deploy.

**Done when**

- [x] We have checked that the sentry deploy template defines a version of postgres higher than 9.3
- [x] We have run the template to check whether it works
- [x] Then we have a discussion on what that looks like

**Comment by jasonBirchall** [comment]
https://github.com/ministryofjustice/sentry-deploy/blob/4f8324be505f69015530d0b66c160a2e796d4419/cloudformation/sentry_staging.yaml#L74

Version 9.5 in the sentry deploy repo.

**Comment by jasonBirchall** [comment]
Confirmed that the Template Deploy CFN command (that updates stack level IaC) is not working and hasn't worked for years. We cannot perform a CFN update.

**Comment by jasonBirchall** [comment]
Recommended practice is to update via the CloudFormation stack.

**Comment by jasonBirchall** [comment]
Conclusion of this ticket: 
The Cloudformation for Sentry 'staging' and 'prod' does define the postgres version in the repo. However, there is no way to update this via Template Deploy due to the broken functionality of `cfn update` (unknown reasons at this point). The recommended way to update the Sentry postgres version is either manually or via the Cloudformation stack. 

The support team will arrange a time to perform a manual backup of the current running Sentry 'staging' DB and then perform the upgrade via Cloudformation. This will be completed in another ticket.
