### ISSUE TITLE
Remove our ECR policy and add monitoring/alerting of Docker image counts

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#905]
We currently have a limit of 100 docker images per ECR. There is also a hard limit, set by AWS, of 1,000 images per ECR, and 1,000 ECRs total.

Igor Ushkarev pointed out a problem with this. See [this issue](https://github.com/ministryofjustice/cloud-platform/issues/839) for details.

Briefly, imagine a team, using a single ECR, whose service requires 2 images; `rails-app` and `worker`, stored in the ECR as `[ECR]:rails-app-[tag]` and `[ECR]:worker-[tag]`

Let's say `worker` is quite straightforward, and that image is never updated after the first version has been pushed. `rails-app` is where the bulk of the work happens, and that image is updated quite often.

After 100 updates to `rails-app` have been pushed to the ECR, breaching the lifecycle policy, the `[ECR]:worker-1.0` image will be aged out of the ECR, and the next time the image is referenced (e.g. if the cluster is rebalancing load and moving the container to a different node), the image pull step will fail, and the production service will be broken.

To avoid this problem, this ticket proposes removing the lifecycle policy altogether, but adding monitoring and alerting such that we can take action before an ECR runs out of space.

### Definition of done

 - [ ] The ECR lifecycle policy has been removed
 - [ ] The user guide has been updated to remove references to the lifecycle policy
 - [ ] We are gathering metrics about the number of ECRs we have, and the number of images in each of them
 - [ ] We have an 'amber' alert when any ECR contains more than X images
 - [ ] We have a 'red' alert when any ECR contains more than y images
 - [ ] We have an 'amber' alert when the number of ECRs rises above N
 - [ ] We have a 'red' alert when the number of ECRs rises above M
 - [ ] We have an architecture decision record (ADR) documenting this strategy

This ticket will spawn separate tickets for some of these sub-tasks, but it's worth having one ticket to keep track of which parts have been done.

**Comment by vijay-veeranki-moj** [comment]
Completed below tasks

 The ECR lifecycle policy has been removed
 The user guide has been updated to remove references to the lifecycle policy

**Comment by vijay-veeranki-moj** [comment]
Created a new ticket for Gathering metrics about the number of ECRs we have, and the number of images in each of them, and send Alerts as defined in here. That needs to Create Custom Prometheus Exporters for ECR Alerts #985.

https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/985

**Comment by vijay-veeranki-moj** [comment]
Below is the reply from aws, for the service request raised asking if they can guide how to use cloud watch to get the alerts for ecr.

Hello,

Thanks for your time on chat today. It was pleasure assisting you.

To summarize during the chat we discussed that you wanted to setup cloudwatch alert on the number of images in ECR and get SNS notification whenever a threshold is breached. As discussed we do not have a default metrics for ECR in cloudwatch which can be integrated with SNS. In this case as discussed you would need to either run a describe image call [1] or list image call [2] via a script in lambda function along with count function, and send an SNS notification as a target of lambda. Since cloudwatch events are only configured to monitor any changes in the configuration, or when the API call is logged via cloudtrail hence if you decide to use cloudwatch events on putimage API call [3] and configure lambda as target, you would still need to run the script

[1] https://docs.aws.amazon.com/cli/latest/reference/ecr/describe-images.html
[2] https://docs.aws.amazon.com/cli/latest/reference/ecr/list-images.html
[3] https://docs.aws.amazon.com/cli/latest/reference/ecr/put-image.html

Please feel free to reach back for any follow up questions.

Good Day.

Best regards,

Anam K.
Amazon Web Services
